# -*- coding: utf-8 -*-
"""
================================================================================
V5 DCA + AI Hybrid 動態濾網 Fixed LSTM 回測
(Dynamic Regime Filter + Fixed LSTM Backtest)
================================================================================
結合 DCA Hybrid 策略與固定 LSTM 模型功能，並加入「動態體制濾網」。

**動態濾網邏輯 (Dynamic Regime Filter)**:
1. **熊市定義 (Bear Mode)**: 收盤價 < MA120 持續達到 3 天。
   - 目的：確認趨勢轉空，濾掉單日插針 (False Alarm)。
   - 一旦進入 Bear Mode，必須等到價格重新站上 MA120 才解除。

2. **濾網行為 (Filter Action)**:
   - **Bull Mode (牛市)**: 不使用濾網 (No Filter)，完全依照 AI 判斷。
   - **Bear Mode (熊市)**: 強制啟用 **10日 High 濾網 (Donchian Filter)**。
     - AI 想買時，必須確認 `Close > Max(High of last 10 days)` 才能執行。

**Fixed LSTM 特點**:
- 使用與 V5 No Filter 相同的 _fixed 模型，確保 AI 原始決策一致，只改變執行邏輯。

LSTM 訓練設定：
- T+1:  過去 2000 天
- T+5:  過去 2200 天
- T+20: 過去 2400 天
- split_ratio: 0.99 (全量訓練)

作者：Phil Liang (Generated by Gemini)
日期：2025-12-28
================================================================================
"""

import os
import sys
import pickle
import argparse
import subprocess
import glob
from datetime import datetime, timedelta

# Windows UTF-8 設定
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from stable_baselines3 import PPO

# 中文字型設定
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

# =============================================================================
# 設定
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
V5_MODELS_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v5')
RESULTS_PATH = os.path.join(PROJECT_PATH, 'results_backtest_v5_dca_hybrid_dynamic_filter_fixed_lstm')
CACHE_DIR = os.path.join(PROJECT_PATH, 'data', 'processed')

# [v6.0] LSTM 已移除 - 以下設定已刪除:
# FIXED_LSTM_SUFFIX, SCRIPT_1D/5D/20D, TRAIN_DAYS_*, TRAIN_SPLIT_RATIO

DEFAULT_START_DATE = '2017-10-16'  # V6.02: 驗證集起始日
DEFAULT_END_DATE = '2023-10-15'    # V6.02: 驗證集結束日
YEARLY_CAPITAL = 600_000  
MONTHLY_DCA_BENCHMARK = 50_000  


def parse_args():
    parser = argparse.ArgumentParser(
        description='V5 DCA + AI Hybrid Dynamic Filter Fixed LSTM Backtest',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument('--start', type=str, default=DEFAULT_START_DATE)
    parser.add_argument('--end', type=str, default=DEFAULT_END_DATE)
    parser.add_argument('--sell-threshold', type=float, default=0.6, help='Confidence threshold for sell signals')
    parser.add_argument('--buy-consensus-threshold', type=float, default=0.5, help='Buy confidence threshold to veto sell signals')
    return parser.parse_args()


# [v6.0] LSTM 已移除 - 以下函式已刪除:
# - get_fixed_lstm_paths()
# - check_fixed_lstm_exists()  
# - train_and_save_fixed_lstm()
# - find_or_train_fixed_lstm()
# - load_fixed_lstm_models()
# - save_lstm_info()



# =============================================================================
# Strategy 1: Shared Pool + 2x Leverage on Drawdown (大跌時啟動槓桿)
# =============================================================================
class LeveragedSharedPoolBacktester:
    """
    與 Strategy 2 相同的 Shared Pool 架構，但新增 2x 槓桿功能：
    - 當大盤從歷史高點下跌超過 8% 時，啟動 2x 槓桿模式 (與停損點一致)
    - 在 2x 模式期間買入的倉位（DCA 和 AI 都適用），其漲跌幅以 2 倍計算
    - 當大盤漲回到啟動 2x 模式的點位時，結束 2x 模式
    - 已買入的 2x 倉位維持 2x，直到該倉位被賣出
    """
    
    LEVERAGE_THRESHOLD = 0.08  # 下跌 8% 啟動槓桿 (與停損點一致)
    
    def __init__(self, buy_model, sell_model, yearly_capital=600_000,
                 dca_amount=50_000, ai_chunk_amount=50_000,
                 sell_threshold=0.6, buy_consensus_threshold=0.5):
        self.buy_model = buy_model
        self.sell_model = sell_model
        self.yearly_capital = yearly_capital
        self.dca_amount = dca_amount
        self.ai_chunk_amount = ai_chunk_amount
        self.sell_threshold = sell_threshold
        self.buy_consensus_threshold = buy_consensus_threshold
        
        self.trades = []
        self.equity_curve = []
        self.dca_buy_signals = []      
        self.ai_buy_signals = []       
        self.ai_sell_signals = []
        self.filtered_signals = []
        self.daily_confidence = []
        self.daily_action_summary = []
        self.open_positions = []
        self.total_invested = 0
        
        # 槓桿追蹤
        self.leverage_events = []  # 記錄槓桿啟動/結束事件
        self.leverage_periods = []  # 記錄槓桿期間 (start_date, end_date)

    def run(self, df: pd.DataFrame, feature_cols: list) -> dict:
        features = df[feature_cols].values.astype(np.float32)
        close_prices = df['Close'].values
        dates = df.index
        
        # =========== 動態濾網：讀取必要數據 ===========
        # 1. Donchian Filter (for Bear Mode)
        if 'Signal_Buy_Filter' not in df.columns:
            print("[Warning] Signal_Buy_Filter missing, assuming True")
            donchian_signals = np.ones(len(df), dtype=bool)
        else:
            donchian_signals = df['Signal_Buy_Filter'].values.astype(bool)
        
        # 2. MA120 for Regime Detection
        if 'MA120' not in df.columns:
            print("[Error] MA120 not found in dataframe! Please update ptrl_hybrid_system.py")
            return {}
        ma120_values = df['MA120'].values
        
        # =========== 動態資金分配 ===========
        yearly_pool = 0
        dca_positions = []
        ai_positions = []
        
        current_year = None
        last_dca_month = None
        dynamic_chunk_amount = self.dca_amount
        
        # 2x 槓桿追蹤
        leveraged_mode = False
        leverage_trigger_price = 0
        peak_price = close_prices[0]
        current_leverage_start = None
        
        # 體制追蹤 (Dynamic Filter)
        bear_counter = 0     # 連續低於 MA120 天數
        current_regime = 'BULL' # 預設牛市
        self.regime_history = []
        self.filtered_signals = []
        
        print(f"[Strategy 1] Period: {dates[0].strftime('%Y-%m-%d')} ~ {dates[-1].strftime('%Y-%m-%d')}")
        print(f"[Strategy 1] Dynamic Fund Allocation + 2x Leverage on Drawdown")
        print(f"[Strategy 1] Leverage Threshold: -{self.LEVERAGE_THRESHOLD*100:.0f}% from peak")
        print(f"[Strategy 1] MODE: DYNAMIC FILTER (Price < MA120 for 3 days -> Bear Mode)")
        
        for i in range(len(df)):
            date = dates[i]
            price = close_prices[i]
            year = date.year
            month = date.month
            
            # =========== 2x 槓桿邏輯 ===========
            if not leveraged_mode:
                peak_price = max(peak_price, price)
            
            if not leveraged_mode:
                if price < peak_price * (1 - self.LEVERAGE_THRESHOLD):
                    leveraged_mode = True
                    leverage_trigger_price = price
                    current_leverage_start = date
                    self.leverage_events.append({
                        'date': date, 'event': 'START', 'price': price,
                        'peak_price': peak_price, 
                        'drawdown': (peak_price - price) / peak_price * 100
                    })
                    print(f"  🔥 [{date.strftime('%Y-%m-%d')}] 2x 槓桿啟動! 價格 {price:,.0f} (從高點 {peak_price:,.0f} 下跌 {(peak_price-price)/peak_price*100:.1f}%)")
            else:
                if price >= leverage_trigger_price:
                    leveraged_mode = False
                    self.leverage_events.append({
                        'date': date, 'event': 'END', 'price': price,
                        'trigger_price': leverage_trigger_price
                    })
                    self.leverage_periods.append((current_leverage_start, date))
                    print(f"  ✅ [{date.strftime('%Y-%m-%d')}] 2x 槓桿結束! 價格 {price:,.0f} (回到觸發點 {leverage_trigger_price:,.0f})")
                    peak_price = price
                    current_leverage_start = None
            
            current_leverage = 2.0 if leveraged_mode else 1.0
            # =========== End 槓桿邏輯 ===========
            
            # =========== 動態體制判斷 (Regime Detection) ===========
            ma120 = ma120_values[i]
            
            if np.isnan(ma120):
                regime = 'BULL'  # 無 MA 數據時假設牛市
            else:
                if price < ma120:
                    bear_counter += 1
                else:
                    bear_counter = 0
                
                # 狀態轉換邏輯
                if current_regime == 'BULL':
                    if bear_counter >= 3:
                        current_regime = 'BEAR'
                else:  # BEAR
                    if price >= ma120:  # 一站回 MA120 立即轉牛
                        current_regime = 'BULL'
            
            self.regime_history.append({'date': date, 'regime': current_regime, 'price': price, 'ma120': ma120})
            
            # 計算動態濾網狀態
            is_bear_mode = (current_regime == 'BEAR')
            pass_donchian = bool(donchian_signals[i])
            pass_dynamic_filter = True  # 預設通過
            if is_bear_mode and not pass_donchian:
                pass_dynamic_filter = False
            # =========== End 體制判斷 ===========
            
            # =========== 年度資金注入 ===========
            if current_year != year:
                current_year = year
                last_dca_month = None
                # 年初注入新資金到池中
                yearly_pool += self.yearly_capital
                self.total_invested += self.yearly_capital
                # 計算剩餘月數 (1月=12個月, 12月=1個月)
                remaining_months = 13 - month
                dynamic_chunk_amount = yearly_pool / remaining_months if remaining_months > 0 else yearly_pool
                print(f"  [{year}] +${self.yearly_capital:,.0f} → Pool: ${yearly_pool:,.0f}, 剩餘{remaining_months}月, 每倉: ${dynamic_chunk_amount:,.0f}")

            # =========== 動態計算每月買入金額 ===========
            # 每月初重新計算 (包含 AI 賣出回收的資金)
            if last_dca_month != month:
                remaining_months = 13 - month  # 1月有12個月, 12月有1個月
                if remaining_months > 0 and yearly_pool > 0:
                    dynamic_chunk_amount = yearly_pool / remaining_months
                else:
                    dynamic_chunk_amount = yearly_pool
                # 確保最低買入金額
                dynamic_chunk_amount = max(dynamic_chunk_amount, 10000)  # 最低 1 萬

            # =========== DCA (Monthly) ===========
            day_dca_shares = 0
            day_dca_leverage = 1.0
            if last_dca_month != month:
                last_dca_month = month
                # 從池中分配資金
                fund = min(dynamic_chunk_amount, yearly_pool)
                if fund > price:  # 至少能買 1 股
                    yearly_pool -= fund
                    shares = int(fund / price)
                    cost = shares * price
                    leftover = fund - cost
                    yearly_pool += leftover  # 零頭放回池中
                    
                    dca_positions.append({
                        'shares': shares, 
                        'buy_price': price, 
                        'buy_idx': i, 
                        'cost': cost,
                        'leverage': current_leverage
                    })
                    day_dca_shares = shares
                    day_dca_leverage = current_leverage
                    self.dca_buy_signals.append((date, price, shares, current_leverage))
            
            # AI
            obs = np.nan_to_num(features[i], nan=0.0, posinf=1.0, neginf=-1.0)
            
            # 當日追蹤變數
            day_action = 'HOLD'
            day_buy_conf = None
            day_sell_conf = None
            day_note = ''
            day_sold_count = 0
            day_bought_shares = 0
            day_ai_leverage = 1.0

            # 🔥 Agent Consensus: 每日必須取得 Buy Agent 的信心度 (即使 Dynamic Filter 有開啟，這裡主要用於 Consensus)
            current_obs = obs.reshape(1, -1)
            buy_action_pred, _ = self.buy_model.predict(current_obs, deterministic=True)
            buy_probs = self.buy_model.policy.get_distribution(self.buy_model.policy.obs_to_tensor(current_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
            current_buy_conf = float(buy_probs[1]) if buy_action_pred[0] == 1 else float(buy_probs[0])
            day_buy_conf = current_buy_conf
            
            # 檢查持倉賣出 (AI positions)
            max_sell_conf_today = 0
            for idx in range(len(ai_positions) - 1, -1, -1):
                pos = ai_positions[idx]
                hold_days = i - pos['buy_idx']
                
                # 計算槓桿後的報酬率 (用於 sell agent observation)
                base_return = price / pos['buy_price']
                leveraged_return = 1 + (base_return - 1) * pos['leverage']
                
                sell_obs = np.concatenate([obs, [leveraged_return]]).astype(np.float32).reshape(1, -1)
                action, _ = self.sell_model.predict(sell_obs, deterministic=True)
                
                sell_probs = self.sell_model.policy.get_distribution(self.sell_model.policy.obs_to_tensor(sell_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
                sell_conf = float(sell_probs[1]) if action[0] == 1 else float(sell_probs[0])
                max_sell_conf_today = max(max_sell_conf_today, sell_conf)
                
                log_entry = {'date': date, 'status': 'holding', 'price': price, 'sell_conf': sell_conf, 'buy_conf': current_buy_conf, 'action': 'hold', 'leverage': pos['leverage']}
                self.daily_confidence.append(log_entry)
                
                # 賣出條件：(AI 決定賣出 且 無共識否決) 或 槓桿後報酬 < 0.92 (強制停損)
                is_stop_loss = leveraged_return < 0.92
                is_sell_signal = (action[0] == 1 and sell_conf > self.sell_threshold)
                
                # 共識檢查
                is_consensus_hold = False
                if is_sell_signal and not is_stop_loss:
                    # 🔥 只有當 Buy Agent 真心想買 (Action=1) 且信心夠高時，才否決賣出
                    if buy_action_pred[0] == 1 and current_buy_conf > self.buy_consensus_threshold:
                        is_consensus_hold = True

                if (is_sell_signal and not is_consensus_hold) or is_stop_loss:
                    log_entry['action'] = 'SELL'
                    # 計算實際收益 (考慮槓桿)
                    leveraged_value = pos['cost'] * leveraged_return
                    profit = leveraged_value - pos['cost']
                    # 🔥 賣出收益回到 yearly_pool，可用於後續買入
                    yearly_pool += leveraged_value
                    
                    self.trades.append({
                        'type': 'AI_S1', 
                        'return': leveraged_return - 1, 
                        'base_return': base_return - 1,
                        'profit': profit, 
                        'hold_days': hold_days,
                        'leverage': pos['leverage']
                    })
                    self.ai_sell_signals.append({'date': date, 'price': price, 'confidence': sell_conf, 'leverage': pos['leverage']})
                    ai_positions.pop(idx)
                    day_action = 'SELL'
                    day_sell_conf = sell_conf
                    day_sold_count += 1

            # 檢查買入 (動態濾網模式)
            
            # 🔥 使用動態計算的買入金額
            if yearly_pool >= dynamic_chunk_amount and dynamic_chunk_amount > price:
                # buy_conf 已經在上面計算了 (current_buy_conf)
                # 直接使用 current_buy_conf
                
                log_entry = {'date': date, 'status': 'check_buy', 'price': price, 'buy_conf': current_buy_conf, 'action': 'wait', 'leverage': current_leverage, 'regime': current_regime, 'filter_pass': pass_dynamic_filter}
                self.daily_confidence.append(log_entry)

                if buy_action_pred[0] == 1:
                    # AI 想買 - 檢查動態濾網
                    if pass_dynamic_filter:
                        fund = min(dynamic_chunk_amount, yearly_pool)
                        if fund > price:
                            yearly_pool -= fund
                            log_entry['action'] = 'BUY'
                            shares = int(fund / price)
                            cost = shares * price
                            leftover = fund - cost
                            yearly_pool += leftover  # 零頭放回池中
                            ai_positions.append({
                                'shares': shares, 
                                'buy_price': price, 
                                'buy_idx': i, 
                                'cost': cost,
                                'leverage': current_leverage
                            })
                            self.ai_buy_signals.append({'date': date, 'price': price, 'confidence': current_buy_conf, 'leverage': current_leverage})
                            day_action = 'BUY'
                            day_bought_shares = shares
                            day_ai_leverage = current_leverage
                    else:
                        # 被濾網擋下
                        log_entry['action'] = 'FILTERED'
                        self.filtered_signals.append({'date': date, 'price': price, 'confidence': current_buy_conf, 'regime': current_regime})
            
            # 產生當日摘要
            dca_position_count = len(dca_positions)
            notes = []
            
            if day_dca_shares > 0:
                lev_str = f"({day_dca_leverage:.0f}x)" if day_dca_leverage > 1 else ""
                notes.append(f'DCA+1倉{lev_str}')
            if day_sold_count > 0:
                notes.append(f'AI-{day_sold_count}倉')
            if day_bought_shares > 0:
                lev_str = f"({day_ai_leverage:.0f}x)" if day_ai_leverage > 1 else ""
                notes.append(f'AI+1倉{lev_str}')
            
            # 計算 2x 倉數
            dca_2x_count = sum(1 for p in dca_positions if p['leverage'] > 1)
            ai_2x_count = sum(1 for p in ai_positions if p['leverage'] > 1)
            total_positions = dca_position_count + len(ai_positions)
            total_2x = dca_2x_count + ai_2x_count
            
            lev_status = "🔥2x" if leveraged_mode else ""
            notes.append(f'現{total_positions}倉(DCA{dca_position_count}+AI{len(ai_positions)})[2x:{total_2x}]{lev_status}')
            
            day_note = ', '.join(notes)
            
            if day_sell_conf is None and len(ai_positions) > 0:
                day_sell_conf = max_sell_conf_today if max_sell_conf_today > 0 else None
            
            self.daily_action_summary.append({
                'date': date,
                'ai_action': day_action,
                'price': price,
                'ai_buy_conf': day_buy_conf,
                'ai_sell_conf': day_sell_conf,
                'ai_position_count': len(ai_positions),
                'dca_position_count': dca_position_count,
                'total_position_count': total_positions,
                'leveraged_mode': leveraged_mode,
                'current_leverage': current_leverage,
                'positions_2x': total_2x,
                'note': day_note
            })

            # 計算總市值 (考慮槓桿)
            dca_val = sum(
                p['cost'] * (1 + (price / p['buy_price'] - 1) * p['leverage'])
                for p in dca_positions
            )
            ai_val = sum(
                p['cost'] * (1 + (price / p['buy_price'] - 1) * p['leverage'])
                for p in ai_positions
            )
            total_val = dca_val + ai_val + yearly_pool
            
            self.equity_curve.append({'date': date, 'value': total_val, 'leveraged_mode': leveraged_mode})
        
        # 如果回測結束時還在槓桿模式，記錄未結束的期間
        if leveraged_mode and current_leverage_start:
            self.leverage_periods.append((current_leverage_start, dates[-1]))
        
        # 保存未平倉持倉
        self.open_positions = []
        for pos in ai_positions:
            self.open_positions.append({
                'buy_date': dates[pos['buy_idx']].strftime('%Y-%m-%d'),
                'buy_price': pos['buy_price'],
                'shares': pos['shares'],
                'cost': pos['cost'],
                'leverage': pos['leverage']
            })
            
        return self._calculate_metrics()

    def _calculate_metrics(self) -> dict:
        if not self.equity_curve: return {}
        equity_df = pd.DataFrame(self.equity_curve).set_index('date')
        final = equity_df['value'].iloc[-1]
        total_return = (final - self.total_invested) / self.total_invested if self.total_invested > 0 else 0
        days = (equity_df.index[-1] - equity_df.index[0]).days
        annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
        daily_ret = equity_df['value'].pct_change().fillna(0)
        sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
        roll_max = equity_df['value'].cummax()
        max_dd = ((equity_df['value'] - roll_max) / roll_max).min()
        
        wins = sum(1 for t in self.trades if t['return'] > 0)
        win_rate = wins / len(self.trades) if self.trades else 0
        
        # 槓桿統計
        leverage_2x_buys = sum(1 for s in self.ai_buy_signals if s.get('leverage', 1) > 1)
        leverage_2x_buys += sum(1 for s in self.dca_buy_signals if len(s) > 3 and s[3] > 1)
        
        return {
            'total_invested': self.total_invested,
            'final_value': final,
            'total_return': total_return,
            'annualized_return': annualized,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_dd,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'equity_df': equity_df,
            'dca_buys': len(self.dca_buy_signals),
            'ai_buys': len(self.ai_buy_signals),
            'leverage_events': len(self.leverage_events),
            'leverage_2x_buys': leverage_2x_buys,
            'leverage_periods': self.leverage_periods
        }


# =============================================================================
# Strategy 2: Shared Pool (Injection Mode) - WITH FILTER
# =============================================================================
class SharedPoolBacktester:
    def __init__(self, buy_model, sell_model, yearly_capital=600_000, 
                 dca_amount=50_000, ai_chunk_amount=50_000,
                 sell_threshold=0.6, buy_consensus_threshold=0.5):
        self.buy_model = buy_model
        self.sell_model = sell_model
        self.yearly_capital = yearly_capital
        self.dca_amount = dca_amount
        self.ai_chunk_amount = ai_chunk_amount
        self.sell_threshold = sell_threshold
        self.buy_consensus_threshold = buy_consensus_threshold
        
        self.trades = []
        self.equity_curve = []
        self.dca_buy_signals = []      
        self.ai_buy_signals = []       
        self.ai_sell_signals = []
        self.filtered_signals = []     # AI想買但被濾網擋下的訊號
        self.daily_confidence = []
        self.daily_action_summary = []  # 每日操作摘要 (一天一筆)
        self.open_positions = []       # 回測結束時的未平倉 AI 持倉
        self.total_invested = 0

    def run(self, df: pd.DataFrame, feature_cols: list) -> dict:
        features = df[feature_cols].values.astype(np.float32)
        close_prices = df['Close'].values
        dates = df.index
        
        # =========== 動態濾網：讀取必要數據 ===========
        # 1. Donchian Filter (for Bear Mode)
        if 'Signal_Buy_Filter' not in df.columns:
            print("[Warning] Signal_Buy_Filter missing, assuming True")
            donchian_signals = np.ones(len(df), dtype=bool)
        else:
            donchian_signals = df['Signal_Buy_Filter'].values.astype(bool)
        
        # 2. MA120 for Regime Detection
        if 'MA120' not in df.columns:
            print("[Error] MA120 not found in dataframe! Please update ptrl_hybrid_system.py")
            return {}
        ma120_values = df['MA120'].values
        
        # =========== 動態資金分配 ===========
        yearly_pool = 0
        dca_shares = 0
        ai_positions = []      
        
        current_year = None
        last_dca_month = None
        dynamic_chunk_amount = self.dca_amount
        
        # 體制追蹤 (Dynamic Filter)
        bear_counter = 0     # 連續低於 MA120 天數
        current_regime = 'BULL' # 預設牛市
        self.regime_history = []
        
        print(f"[Strategy 2] Period: {dates[0].strftime('%Y-%m-%d')} ~ {dates[-1].strftime('%Y-%m-%d')}")
        print(f"[Strategy 2] Shared Pool (Dynamic Fund Allocation)")
        print(f"[Strategy 2] MODE: DYNAMIC FILTER (Price < MA120 for 3 days -> Bear Mode)")
        
        for i in range(len(df)):
            date = dates[i]
            price = close_prices[i]
            year = date.year
            month = date.month
            
            # =========== 動態體制判斷 (Regime Detection) ===========
            ma120 = ma120_values[i]
            
            if np.isnan(ma120):
                regime = 'BULL'  # 無 MA 數據時假設牛市
            else:
                if price < ma120:
                    bear_counter += 1
                else:
                    bear_counter = 0
                
                # 狀態轉換邏輯
                if current_regime == 'BULL':
                    if bear_counter >= 3:
                        current_regime = 'BEAR'
                else:  # BEAR
                    if price >= ma120:  # 一站回 MA120 立即轉牛
                        current_regime = 'BULL'
            
            self.regime_history.append({'date': date, 'regime': current_regime, 'price': price, 'ma120': ma120})
            
            # 計算動態濾網狀態
            is_bear_mode = (current_regime == 'BEAR')
            pass_donchian = bool(donchian_signals[i])
            pass_dynamic_filter = True  # 預設通過
            if is_bear_mode and not pass_donchian:
                pass_dynamic_filter = False
            # =========== End 體制判斷 ===========
            
            # =========== 年度資金注入 ===========
            if current_year != year:
                current_year = year
                last_dca_month = None
                # 年初注入新資金到池中
                yearly_pool += self.yearly_capital
                self.total_invested += self.yearly_capital
                # 計算剩餘月數 (1月=12個月, 12月=1個月)
                remaining_months = 13 - month
                dynamic_chunk_amount = yearly_pool / remaining_months if remaining_months > 0 else yearly_pool
                print(f"  [{year}] +${self.yearly_capital:,.0f} → Pool: ${yearly_pool:,.0f}, 剩餘{remaining_months}月, 每倉: ${dynamic_chunk_amount:,.0f}")

            # =========== 動態計算每月買入金額 ===========
            # 每月初重新計算 (包含 AI 賣出回收的資金)
            if last_dca_month != month:
                remaining_months = 13 - month  # 1月有12個月, 12月有1個月
                if remaining_months > 0 and yearly_pool > 0:
                    dynamic_chunk_amount = yearly_pool / remaining_months
                else:
                    dynamic_chunk_amount = yearly_pool
                # 確保最低買入金額
                dynamic_chunk_amount = max(dynamic_chunk_amount, 10000)  # 最低 1 萬

            # =========== DCA (Monthly) ===========
            day_dca_shares = 0  # 當日 DCA 買入股數
            if last_dca_month != month:
                last_dca_month = month
                # 從池中分配資金
                fund = min(dynamic_chunk_amount, yearly_pool)
                if fund > price:  # 至少能買 1 股
                    yearly_pool -= fund
                    shares = int(fund / price)
                    cost = shares * price
                    leftover = fund - cost
                    yearly_pool += leftover  # 零頭放回池中
                    
                    dca_shares += shares
                    day_dca_shares = shares
                    self.dca_buy_signals.append((date, price, shares))
            
            # AI
            obs = np.nan_to_num(features[i], nan=0.0, posinf=1.0, neginf=-1.0)
            
            # 當日追蹤變數
            day_action = 'HOLD'
            day_buy_conf = None
            day_sell_conf = None
            day_note = ''
            day_sold_count = 0
            day_bought_shares = 0
            
            # 🔥 Agent Consensus: 每日必須取得 Buy Agent 的信心度
            current_obs = obs.reshape(1, -1)
            buy_action_pred, _ = self.buy_model.predict(current_obs, deterministic=True)
            buy_probs = self.buy_model.policy.get_distribution(self.buy_model.policy.obs_to_tensor(current_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
            current_buy_conf = float(buy_probs[1]) if buy_action_pred[0] == 1 else float(buy_probs[0])
            day_buy_conf = current_buy_conf

            # 檢查持倉賣出
            max_sell_conf_today = 0
            for idx in range(len(ai_positions) - 1, -1, -1):
                pos = ai_positions[idx]
                hold_days = i - pos['buy_idx']
                current_return = price / pos['buy_price']
                sell_obs = np.concatenate([obs, [current_return]]).astype(np.float32).reshape(1, -1)
                action, _ = self.sell_model.predict(sell_obs, deterministic=True)
                
                sell_probs = self.sell_model.policy.get_distribution(self.sell_model.policy.obs_to_tensor(sell_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
                sell_conf = float(sell_probs[1]) if action[0] == 1 else float(sell_probs[0])
                max_sell_conf_today = max(max_sell_conf_today, sell_conf)
                
                log_entry = {'date': date, 'status': 'holding', 'price': price, 'sell_conf': sell_conf, 'buy_conf': current_buy_conf, 'action': 'hold'}
                self.daily_confidence.append(log_entry)
                
                is_stop_loss = current_return < 0.92
                is_sell_signal = (action[0] == 1 and sell_conf > self.sell_threshold)
                
                # 共識檢查
                is_consensus_hold = False
                if is_sell_signal and not is_stop_loss:
                    # 🔥 只有當 Buy Agent 真心想買 (Action=1) 且信心夠高時，才否決賣出
                    if buy_action_pred[0] == 1 and current_buy_conf > self.buy_consensus_threshold:
                        is_consensus_hold = True

                if (is_sell_signal and not is_consensus_hold) or is_stop_loss:
                    log_entry['action'] = 'SELL'
                    proceeds = pos['shares'] * price
                    profit = proceeds - pos['cost']
                    # 🔥 賣出收益回到 yearly_pool，可用於後續買入
                    yearly_pool += proceeds 
                    self.trades.append({'type': 'AI_S2', 'return': current_return - 1, 'profit': profit, 'hold_days': hold_days})
                    self.ai_sell_signals.append({'date': date, 'price': price, 'confidence': sell_conf})
                    ai_positions.pop(idx)
                    day_action = 'SELL'
                    day_sell_conf = sell_conf
                    day_sold_count += 1

            # 檢查買入 (動態濾網模式)
            
            # 🔥 使用動態計算的買入金額
            if yearly_pool >= dynamic_chunk_amount and dynamic_chunk_amount > price:
                # current_buy_conf 已經在上面計算了
                
                log_entry = {'date': date, 'status': 'check_buy', 'price': price, 'buy_conf': current_buy_conf, 'action': 'wait', 'regime': current_regime, 'filter_pass': pass_dynamic_filter}
                self.daily_confidence.append(log_entry)

                if buy_action_pred[0] == 1:
                    # AI 想買 - 檢查動態濾網
                    if pass_dynamic_filter:
                        fund = min(dynamic_chunk_amount, yearly_pool)
                        if fund > price:
                            yearly_pool -= fund
                            log_entry['action'] = 'BUY'
                            shares = int(fund / price)
                            cost = shares * price
                            leftover = fund - cost
                            yearly_pool += leftover  # 零頭放回池中
                            ai_positions.append({'shares': shares, 'buy_price': price, 'buy_idx': i, 'cost': cost})
                            self.ai_buy_signals.append({'date': date, 'price': price, 'confidence': current_buy_conf})
                            day_action = 'BUY'
                            day_bought_shares = shares
                    else:
                        # 被濾網擋下
                        log_entry['action'] = 'FILTERED'
                        self.filtered_signals.append({'date': date, 'price': price, 'confidence': current_buy_conf, 'regime': current_regime})
            
            # 產生當日摘要 - 格式: DCA買賣, AI買賣, 總倉數
            # DCA 視為每月買1倉 (50k), AI 每筆買1倉 (50k)
            dca_position_count = len(self.dca_buy_signals)  # DCA買入次數=DCA倉數
            notes = []
            
            # 分別追蹤 DCA、AI賣出、AI買入 (不用 day_action，避免被覆蓋)
            if day_dca_shares > 0:
                notes.append('DCA+1倉')
            if day_sold_count > 0:
                notes.append(f'AI-{day_sold_count}倉')
            if day_bought_shares > 0:
                notes.append('AI+1倉')
            
            # 總倉數 = DCA倉 + AI倉
            total_positions = dca_position_count + len(ai_positions)
            notes.append(f'現{total_positions}倉(DCA{dca_position_count}+AI{len(ai_positions)})')
            
            day_note = ', '.join(notes)
            
            # 如果沒有買進但有檢查買入，記錄買入信心
            if day_sell_conf is None and len(ai_positions) > 0:
                day_sell_conf = max_sell_conf_today if max_sell_conf_today > 0 else None
            
            self.daily_action_summary.append({
                'date': date,
                'ai_action': day_action,
                'price': price,
                'ai_buy_conf': day_buy_conf,
                'ai_sell_conf': day_sell_conf,
                'ai_position_count': len(ai_positions),
                'dca_position_count': dca_position_count,
                'total_position_count': total_positions,
                'note': day_note
            })

            # Value = Stock + Yearly Pool
            dca_val = dca_shares * price
            ai_val = sum(p['shares'] * price for p in ai_positions)
            total_val = dca_val + ai_val + yearly_pool
            
            self.equity_curve.append({'date': date, 'value': total_val})
        
        # 保存未平倉持倉 (用於 intraday 腳本讀取)
        self.open_positions = []
        for pos in ai_positions:
            self.open_positions.append({
                'buy_date': dates[pos['buy_idx']].strftime('%Y-%m-%d'),
                'buy_price': pos['buy_price'],
                'shares': pos['shares'],
                'cost': pos['cost']
            })
            
        return self._calculate_metrics()

    def _calculate_metrics(self) -> dict:
        if not self.equity_curve: return {}
        equity_df = pd.DataFrame(self.equity_curve).set_index('date')
        final = equity_df['value'].iloc[-1]
        total_return = (final - self.total_invested) / self.total_invested if self.total_invested > 0 else 0
        days = (equity_df.index[-1] - equity_df.index[0]).days
        annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
        daily_ret = equity_df['value'].pct_change().fillna(0)
        sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
        roll_max = equity_df['value'].cummax()
        max_dd = ((equity_df['value'] - roll_max) / roll_max).min()
        
        wins = sum(1 for t in self.trades if t['return'] > 0)
        win_rate = wins / len(self.trades) if self.trades else 0
        return {
            'total_invested': self.total_invested,
            'final_value': final,
            'total_return': total_return,
            'annualized_return': annualized,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_dd,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'equity_df': equity_df,
            'dca_buys': len(self.dca_buy_signals),
            'ai_buys': len(self.ai_buy_signals)
        }


def calculate_pure_dca(df: pd.DataFrame, monthly_amount: float = 50_000):
    close_prices = df['Close'].values
    dates = df.index
    shares = 0
    total_invested = 0
    equity_curve = []
    last_month = None
    leftover_cash = 0  # 累積的零頭
    current_year = None
    
    for i in range(len(df)):
        date = dates[i]
        price = close_prices[i]
        year = date.year
        month = date.month
        
        # 年度變更 - 重置 leftover (新年度開始)
        if current_year != year:
            current_year = year
            leftover_cash = 0  # 新年度開始，重置零頭池
        
        if last_month != month:
            last_month = month
            # 正常月投入
            fund = monthly_amount
            shares_to_buy = int(fund / price)
            if shares_to_buy > 0:
                cost = shares_to_buy * price
                leftover_cash += (fund - cost)  # 累積零頭
                shares += shares_to_buy
                total_invested += cost
            else:
                leftover_cash += fund  # 股價太高，整個月都累積
            
            # 每年 12 月底：用累積的零頭一次買入
            if month == 12:
                extra_shares = int(leftover_cash / price)
                if extra_shares > 0:
                    extra_cost = extra_shares * price
                    shares += extra_shares
                    total_invested += extra_cost
                    leftover_cash -= extra_cost  # 剩餘的零頭繼續保留
                
        equity_curve.append({'date': date, 'value': shares * price})
    
    equity_df = pd.DataFrame(equity_curve).set_index('date')
    final = equity_df['value'].iloc[-1]
    total_return = (final - total_invested) / total_invested if total_invested > 0 else 0
    
    days = (equity_df.index[-1] - equity_df.index[0]).days
    annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
    daily_ret = equity_df['value'].pct_change().fillna(0)
    sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
    max_dd = ((equity_df['value'] - equity_df['value'].cummax()) / equity_df['value'].cummax()).min()
    
    return {
        'total_invested': total_invested, 'final_value': final, 'total_return': total_return,
        'annualized_return': annualized, 'sharpe_ratio': sharpe, 'max_drawdown': max_dd, 'equity_df': equity_df
    }


def calculate_yearly_lumpsum(df: pd.DataFrame, yearly_amount: float = 600_000):
    close_prices = df['Close'].values
    dates = df.index
    shares = 0
    total_invested = 0
    equity_curve = []
    current_year = None
    
    for i in range(len(df)):
        date = dates[i]
        price = close_prices[i]
        year = date.year
        if current_year != year:
            current_year = year
            shares_to_buy = int(yearly_amount / price)
            if shares_to_buy > 0:
                shares += shares_to_buy
                total_invested += shares_to_buy * price
        equity_curve.append({'date': date, 'value': shares * price})
    
    equity_df = pd.DataFrame(equity_curve).set_index('date')
    final = equity_df['value'].iloc[-1]
    total_return = (final - total_invested) / total_invested if total_invested > 0 else 0
    days = (equity_df.index[-1] - equity_df.index[0]).days
    annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
    daily_ret = equity_df['value'].pct_change().fillna(0)
    sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
    max_dd = ((equity_df['value'] - equity_df['value'].cummax()) / equity_df['value'].cummax()).min()
    
    return {
        'total_invested': total_invested, 'final_value': final, 'total_return': total_return,
        'annualized_return': annualized, 'sharpe_ratio': sharpe, 'max_drawdown': max_dd, 'equity_df': equity_df
    }


def main():
    args = parse_args()
    start_date = pd.Timestamp(args.start)
    end_date = pd.Timestamp(args.end) if args.end else None
    
    # [v6.02] 當結束日期比開始日期早時，自動使用今天的日期
    if end_date and end_date < start_date:
        end_date = pd.Timestamp.now().normalize()
        print(f"[Notice] 預設結束日期早於開始日期，已自動調整為今天: {end_date.date()}")
    
    print("=" * 70)
    print("V5 DCA + AI Hybrid 動態濾網回測")
    print("(Dynamic Regime Filter Backtest)")
    print("=" * 70)
    print(f"  📅 回測開始日期: {start_date.date()}")
    print(f"  📅 回測結束日期: {end_date.date() if end_date else '最新資料'}")
    print(f"  ⚙️ Sell Threshold: {args.sell_threshold}")
    print(f"  ⚙️ Buy Consensus Threshold: {args.buy_consensus_threshold}")
    # [v6.0] LSTM 已移除
    
    os.makedirs(RESULTS_PATH, exist_ok=True)
    
    print("\n[Model] Loading V5 models...")
    buy_model = PPO.load(os.path.join(V5_MODELS_PATH, 'ppo_buy_twii_final.zip'))
    sell_model = PPO.load(os.path.join(V5_MODELS_PATH, 'ppo_sell_twii_final.zip'))
    
    print("\n[Data] Loading data...")
    import ptrl_hybrid_system as hybrid
    
    # [v6.0] 不再載入 LSTM 模型，直接計算特徵
    print("  [Compute] 計算特徵...")
    twii_raw = hybrid._load_local_twii_data(start_date="2000-01-01")
    twii_full_df = hybrid.calculate_features(twii_raw, twii_raw, ticker="^TWII", use_cache=False)
    
    twii_backtest_df = twii_full_df[twii_full_df.index >= start_date]
    if end_date: twii_backtest_df = twii_backtest_df[twii_backtest_df.index <= end_date]
    
    # [v6.02] 新增資料可用性檢查
    if len(twii_backtest_df) == 0:
        print(f"\n[Error] 沒有找到指定日期範圍內的資料！")
        print(f"  指定範圍: {start_date.date()} ~ {end_date.date() if end_date else '最新'}")
        print(f"  本地資料範圍: {twii_full_df.index[0].date()} ~ {twii_full_df.index[-1].date()}")
        print(f"\n💡 提示: 請執行 'python update_twii_data.py' 更新本地資料，或調整 --start/--end 參數。")
        return
    
    print("\n[Backtest] Running Strategy 1: Shared Pool + 2x Leverage on Drawdown...")
    bt1 = LeveragedSharedPoolBacktester(
        buy_model, 
        sell_model, 
        YEARLY_CAPITAL,
        sell_threshold=args.sell_threshold,
        buy_consensus_threshold=args.buy_consensus_threshold
    )
    m1 = bt1.run(twii_backtest_df, hybrid.FEATURE_COLS)

    print("\n[Backtest] Running Strategy 2: Shared Pool...")
    bt2 = SharedPoolBacktester(
        buy_model, 
        sell_model, 
        YEARLY_CAPITAL,
        sell_threshold=args.sell_threshold,
        buy_consensus_threshold=args.buy_consensus_threshold
    )
    m2 = bt2.run(twii_backtest_df, hybrid.FEATURE_COLS)
    
    print("\n[Benchmark] Calculating benchmarks...")
    dca_bench = calculate_pure_dca(twii_backtest_df, MONTHLY_DCA_BENCHMARK)
    lump_bench = calculate_yearly_lumpsum(twii_backtest_df, YEARLY_CAPITAL)
    
    print("\n" + "=" * 120)
    print("Performance Comparison: Strat 1 (2x Leverage) vs Strat 2 (Shared Pool) vs Benchmarks")
    print("=" * 120)
    print(f"{'Metric':<20} {'Strat 1 (2x Lev)':>22} {'Strat 2 (Shared)':>22} {'Pure DCA (50k)':>20} {'Yearly Lump Sum':>20}")
    print("-" * 120)
    print(f"{'Total Invested':<20} ${m1['total_invested']:>20,.0f} ${m2['total_invested']:>20,.0f} ${dca_bench['total_invested']:>18,.0f} ${lump_bench['total_invested']:>18,.0f}")
    print(f"{'Final Value':<20} ${m1['final_value']:>20,.0f} ${m2['final_value']:>20,.0f} ${dca_bench['final_value']:>18,.0f} ${lump_bench['final_value']:>18,.0f}")
    print(f"{'Total Return':<20} {m1['total_return']*100:>21.2f}% {m2['total_return']*100:>21.2f}% {dca_bench['total_return']*100:>19.2f}% {lump_bench['total_return']*100:>19.2f}%")
    print(f"{'Annualized Return':<20} {m1['annualized_return']*100:>21.2f}% {m2['annualized_return']*100:>21.2f}% {dca_bench['annualized_return']*100:>19.2f}% {lump_bench['annualized_return']*100:>19.2f}%")
    print(f"{'Sharpe Ratio':<20} {m1['sharpe_ratio']:>22.2f} {m2['sharpe_ratio']:>22.2f} {dca_bench['sharpe_ratio']:>20.2f} {lump_bench['sharpe_ratio']:>20.2f}")
    print(f"{'Max Drawdown':<20} {m1['max_drawdown']*100:>21.2f}% {m2['max_drawdown']*100:>21.2f}% {dca_bench['max_drawdown']*100:>19.2f}% {lump_bench['max_drawdown']*100:>19.2f}%")
    print("-" * 120)
    print(f"{'DCA Buys':<20} {m1['dca_buys']:>22} {m2['dca_buys']:>22}")
    print(f"{'AI Trades':<20} {m1['total_trades']:>22} {m2['total_trades']:>22}")
    print(f"{'AI Win Rate':<20} {m1['win_rate']*100:>21.1f}% {m2['win_rate']*100:>21.1f}%")
    print("-" * 120)
    # Strategy 1 專屬槓桿統計
    print(f"{'2x Leverage Events':<20} {m1.get('leverage_events', 0):>22}")
    print(f"{'2x Leverage Buys':<20} {m1.get('leverage_2x_buys', 0):>22}")
    if m1.get('leverage_periods'):
        print(f"{'Leverage Periods':<20}")
        for start_dt, end_dt in m1['leverage_periods']:
            print(f"                     📅 {start_dt.strftime('%Y-%m-%d')} ~ {end_dt.strftime('%Y-%m-%d')}")
    print("=" * 120)
    
    # Charts (Updated: 3 Subplots)
    fig, axes = plt.subplots(3, 1, figsize=(16, 18))
    
    # 1. Equity
    ax1 = axes[0]
    ax1.plot(m1['equity_df'].index, m1['equity_df']['value'], label='Strat 1 (2x Leverage)', color='blue', linewidth=2)
    ax1.plot(m2['equity_df'].index, m2['equity_df']['value'], label='Strat 2 (Shared)', color='purple', linewidth=2)
    
    # 標示 2x 槓桿期間 (背景色)
    if m1.get('leverage_periods'):
        for start_dt, end_dt in m1['leverage_periods']:
            ax1.axvspan(start_dt, end_dt, alpha=0.15, color='red', label='2x Leverage Period' if start_dt == m1['leverage_periods'][0][0] else '') 
    ax1.plot(dca_bench['equity_df'].index, dca_bench['equity_df']['value'], label='Pure DCA', color='orange', linewidth=1.5, linestyle='--')
    ax1.plot(lump_bench['equity_df'].index, lump_bench['equity_df']['value'], label='Yearly Lump', color='gray', linewidth=1.5, alpha=0.7)
    date_range_str = f"{twii_backtest_df.index[0].strftime('%Y-%m-%d')} ~ {twii_backtest_df.index[-1].strftime('%Y-%m-%d')}"
    ax1.set_title(f'V4 DCA+AI Hybrid Strategies Comparison ({date_range_str})', fontsize=14)
    ax1.set_ylabel('Portfolio Value ($)')
    ax1.legend(loc='upper left')
    ax1.grid(True, alpha=0.3)
    
    price_slice = twii_backtest_df['Close']
    
    # 2. Strat 1 Signals
    ax2 = axes[1]
    ax2.plot(price_slice.index, price_slice.values, label='^TWII', color='black', linewidth=1)
    # 標示 2x 槓桿期間
    if m1.get('leverage_periods'):
        for start_dt, end_dt in m1['leverage_periods']:
            ax2.axvspan(start_dt, end_dt, alpha=0.15, color='red', label='2x Period' if start_dt == m1['leverage_periods'][0][0] else '')
    
    if bt1.dca_buy_signals:
        # 分開 1x 和 2x DCA 買入
        dca_1x = [(d, p) for d, p, s, lev in bt1.dca_buy_signals if lev == 1.0]
        dca_2x = [(d, p) for d, p, s, lev in bt1.dca_buy_signals if lev > 1.0]
        if dca_1x:
            d1x, p1x = zip(*dca_1x)
            ax2.scatter(d1x, p1x, marker='o', color='cyan', s=30, label='S1: DCA Buy (1x)', alpha=0.6)
        if dca_2x:
            d2x, p2x = zip(*dca_2x)
            ax2.scatter(d2x, p2x, marker='o', color='orange', s=50, label='S1: DCA Buy (2x)', alpha=0.8)
    if bt1.ai_buy_signals:
        # 分開 1x 和 2x AI 買入
        ai_1x = [s for s in bt1.ai_buy_signals if s.get('leverage', 1) == 1.0]
        ai_2x = [s for s in bt1.ai_buy_signals if s.get('leverage', 1) > 1.0]
        if ai_1x:
            ax2.scatter([s['date'] for s in ai_1x], [s['price'] for s in ai_1x], 
                       marker='^', color='blue', s=80, label='S1: AI Buy (1x)')
        if ai_2x:
            ax2.scatter([s['date'] for s in ai_2x], [s['price'] for s in ai_2x], 
                       marker='^', color='red', s=100, label='S1: AI Buy (2x)')
    if bt1.ai_sell_signals:
        ai_sell_dates = [s['date'] for s in bt1.ai_sell_signals]
        ai_sell_prices = [s['price'] for s in bt1.ai_sell_signals]
        ax2.scatter(ai_sell_dates, ai_sell_prices, marker='v', color='green', s=80, label='S1: AI Sell')
    ax2.set_title('Strategy 1 (Shared Pool + 2x Leverage on Drawdown) Trade Signals', fontsize=14)
    ax2.set_ylabel('Price')
    ax2.legend(loc='upper left', fontsize=8)
    ax2.grid(True, alpha=0.3)
    
    # 3. Strat 2 Signals
    ax3 = axes[2]
    ax3.plot(price_slice.index, price_slice.values, label='^TWII', color='black', linewidth=1)
    if bt2.dca_buy_signals:
        dca_dates, dca_prices, _ = zip(*bt2.dca_buy_signals)
        ax3.scatter(dca_dates, dca_prices, marker='o', color='orange', s=30, label='S2: DCA Buy', alpha=0.6)
    if bt2.ai_buy_signals:
        ai_buy_dates = [s['date'] for s in bt2.ai_buy_signals]
        ai_buy_prices = [s['price'] for s in bt2.ai_buy_signals]
        ax3.scatter(ai_buy_dates, ai_buy_prices, marker='^', color='purple', s=80, label='S2: AI Buy')
    if bt2.ai_sell_signals:
        ai_sell_dates = [s['date'] for s in bt2.ai_sell_signals]
        ai_sell_prices = [s['price'] for s in bt2.ai_sell_signals]
        ax3.scatter(ai_sell_dates, ai_sell_prices, marker='v', color='green', s=80, label='S2: AI Sell')
    ax3.set_title('Strategy 2 (Shared Pool) Trade Signals', fontsize=14)
    ax3.set_ylabel('Price')
    ax3.legend(loc='upper left')
    ax3.grid(True, alpha=0.3)
    
    plt.tight_layout()
    start_str = twii_backtest_df.index[0].strftime('%Y%m%d')
    end_str = twii_backtest_df.index[-1].strftime('%Y%m%d')
    save_path = os.path.join(RESULTS_PATH, f'backtest_comparison_{start_str}_{end_str}.png')
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"\n[Output] Chart: {save_path}")
    plt.close()
    
    metrics_df = pd.DataFrame({
        'Metric': ['Total_Invested', 'Final_Value', 'Total_Return_Pct', 'Annualized_Return_Pct', 'Sharpe_Ratio', 'Max_Drawdown_Pct', 'DCA_Buys', 'AI_Trades', 'AI_Win_Rate_Pct'],
        'Strat1_Split': [m1['total_invested'], m1['final_value'], m1['total_return']*100, m1['annualized_return']*100, m1['sharpe_ratio'], m1['max_drawdown']*100, m1['dca_buys'], m1['total_trades'], m1['win_rate']*100],
        'Strat2_Shared': [m2['total_invested'], m2['final_value'], m2['total_return']*100, m2['annualized_return']*100, m2['sharpe_ratio'], m2['max_drawdown']*100, m2['dca_buys'], m2['total_trades'], m2['win_rate']*100],
        'Pure_DCA': [dca_bench['total_invested'], dca_bench['final_value'], dca_bench['total_return']*100, dca_bench['annualized_return']*100, dca_bench['sharpe_ratio'], dca_bench['max_drawdown']*100, 'N/A', 'N/A', 'N/A'],
        'Yearly_Lump': [lump_bench['total_invested'], lump_bench['final_value'], lump_bench['total_return']*100, lump_bench['annualized_return']*100, lump_bench['sharpe_ratio'], lump_bench['max_drawdown']*100, 'N/A', 'N/A', 'N/A']
    })
    metrics_path = os.path.join(RESULTS_PATH, f'metrics_comparison_{start_str}_{end_str}.csv')
    metrics_df.to_csv(metrics_path, index=False, encoding='utf-8-sig')
    print(f"[Output] Metrics: {metrics_path}")
    
    if bt2.trades:
        trades_df = pd.DataFrame(bt2.trades)
        trades_path = os.path.join(RESULTS_PATH, f'trades_strat2_{start_str}_{end_str}.csv')
        trades_df.to_csv(trades_path, index=False)
        print(f"[Output] Strat 2 Trades: {trades_path}")

    # New Exports
    if bt1.trades:
        trades1_df = pd.DataFrame(bt1.trades)
        trades1_path = os.path.join(RESULTS_PATH, f'trades_strat1_{start_str}_{end_str}.csv')
        trades1_df.to_csv(trades1_path, index=False)
        print(f"[Output] Strat 1 Trades: {trades1_path}")

    if bt1.daily_confidence:
        conf1_df = pd.DataFrame(bt1.daily_confidence)
        conf1_path = os.path.join(RESULTS_PATH, f'daily_confidence_strat1_{start_str}_{end_str}.csv')
        conf1_df.to_csv(conf1_path, index=False)
        print(f"[Output] Strat 1 Daily Confidence: {conf1_path}")

    if bt2.daily_confidence:
        conf2_df = pd.DataFrame(bt2.daily_confidence)
        conf2_path = os.path.join(RESULTS_PATH, f'daily_confidence_strat2_{start_str}_{end_str}.csv')
        conf2_df.to_csv(conf2_path, index=False)
        print(f"[Output] Strat 2 Daily Confidence: {conf2_path}")

    # =========================================================================
    # 新增：Strategy 2 每日操作報告 (Console + CSV + PNG)
    # =========================================================================
    
    # 1. Console 輸出最近 30 天
    print_daily_action_report(bt2.daily_action_summary, last_n_days=30, strategy_name="Strategy 2 - Shared Pool")
    
    # 2. Daily Action CSV (一天一筆)
    if bt2.daily_action_summary:
        action_df = pd.DataFrame(bt2.daily_action_summary)
        action_path = os.path.join(RESULTS_PATH, f'daily_action_strat2_{start_str}_{end_str}.csv')
        action_df.to_csv(action_path, index=False, encoding='utf-8-sig')
        print(f"[Output] Daily Action CSV: {action_path}")
    
    # 2.5 Open Positions CSV (未平倉持倉，供 intraday 腳本使用)
    if bt2.open_positions:
        pos_df = pd.DataFrame(bt2.open_positions)
        pos_path = os.path.join(RESULTS_PATH, f'open_positions_strat2_{start_str}_{end_str}.csv')
        pos_df.to_csv(pos_path, index=False, encoding='utf-8-sig')
        print(f"[Output] Open Positions CSV: {pos_path}")
        print(f"         未平倉 AI 持倉: {len(bt2.open_positions)} 筆")
    else:
        print(f"[Info] Strat 2 無未平倉 AI 持倉")
    
    # 3. Daily Timeline Chart
    create_daily_timeline_chart(bt2.daily_action_summary, twii_backtest_df, 
                                 os.path.join(RESULTS_PATH, f'daily_timeline_strat2_{start_str}_{end_str}.png'),
                                 leverage_periods=None)
    
    # =========================================================================
    # 新增：Strategy 1 每日操作報告 (Console + CSV + PNG) - 含槓桿資訊
    # =========================================================================
    
    # 1. Console 輸出最近 30 天 (Strategy 1)
    print_daily_action_report(bt1.daily_action_summary, last_n_days=30, strategy_name="Strategy 1 - 2x Leverage on Drawdown")
    
    # 2. Daily Action CSV (一天一筆)
    if bt1.daily_action_summary:
        action1_df = pd.DataFrame(bt1.daily_action_summary)
        action1_path = os.path.join(RESULTS_PATH, f'daily_action_strat1_{start_str}_{end_str}.csv')
        action1_df.to_csv(action1_path, index=False, encoding='utf-8-sig')
        print(f"[Output] Strat 1 Daily Action CSV: {action1_path}")
    
    # 2.5 Open Positions CSV (未平倉持倉)
    if bt1.open_positions:
        pos1_df = pd.DataFrame(bt1.open_positions)
        pos1_path = os.path.join(RESULTS_PATH, f'open_positions_strat1_{start_str}_{end_str}.csv')
        pos1_df.to_csv(pos1_path, index=False, encoding='utf-8-sig')
        print(f"[Output] Strat 1 Open Positions CSV: {pos1_path}")
        print(f"         未平倉 AI 持倉: {len(bt1.open_positions)} 筆")
    else:
        print(f"[Info] Strat 1 無未平倉 AI 持倉")
    
    # 2.6 Leverage Events CSV
    if bt1.leverage_events:
        lev_df = pd.DataFrame(bt1.leverage_events)
        lev_path = os.path.join(RESULTS_PATH, f'leverage_events_strat1_{start_str}_{end_str}.csv')
        lev_df.to_csv(lev_path, index=False, encoding='utf-8-sig')
        print(f"[Output] Leverage Events CSV: {lev_path}")
    
    # 3. Daily Timeline Chart for Strategy 1 (含槓桿期間標示)
    create_daily_timeline_chart(bt1.daily_action_summary, twii_backtest_df, 
                                 os.path.join(RESULTS_PATH, f'daily_timeline_strat1_{start_str}_{end_str}.png'),
                                 leverage_periods=m1.get('leverage_periods'))


def print_daily_action_report(daily_summary: list, last_n_days: int = 30, strategy_name: str = ""):
    """在終端機輸出最近 N 天的操作報告"""
    if not daily_summary:
        return
    
    print("\n" + "=" * 110)
    print(f"📅 每日操作報告 ({strategy_name}) - 最近 {last_n_days} 天")
    print("=" * 110)
    print(f"{'日期':<12} {'AI操作':<6} {'價格':>10} {'買入信心':>10} {'賣出信心':>10} {'2x模式':>6} {'備註':<35}")
    print("-" * 110)
    
    for row in daily_summary[-last_n_days:]:
        icon = {'BUY': '✅', 'SELL': '🔴', 'HOLD': '⏸️'}.get(row['ai_action'], '❓')
        date_str = row['date'].strftime('%Y-%m-%d')
        price_str = f"{row['price']:,.0f}"
        
        buy_conf_str = f"{row['ai_buy_conf']*100:.1f}%" if row['ai_buy_conf'] is not None else "-"
        sell_conf_str = f"{row['ai_sell_conf']*100:.1f}%" if row['ai_sell_conf'] is not None else "-"
        
        # 槓桿模式狀態 (如果有的話)
        lev_mode = row.get('leveraged_mode', None)
        lev_str = "🔥2x" if lev_mode else ("1x" if lev_mode is not None else "-")
        
        print(f"{date_str:<12} {icon} {row['ai_action']:<4} {price_str:>10} {buy_conf_str:>10} {sell_conf_str:>10} {lev_str:>6}  {row['note']:<35}")
    
    print("=" * 110)
    
    # 統計
    recent = daily_summary[-last_n_days:]
    total_days = len(recent)
    buy_count = sum(1 for r in recent if r['ai_action'] == 'BUY')
    sell_count = sum(1 for r in recent if r['ai_action'] == 'SELL')
    hold_count = total_days - buy_count - sell_count
    
    # 最後一天的總倉數
    final_total = recent[-1]['total_position_count'] if recent else 0
    final_dca = recent[-1]['dca_position_count'] if recent else 0
    final_ai = recent[-1]['ai_position_count'] if recent else 0
    final_2x = recent[-1].get('positions_2x', 0) if recent else 0
    
    print(f"統計: 總天數 {total_days} | AI買入 {buy_count} 倉 | AI賣出 {sell_count} 倉 | HOLD {hold_count} 天")
    print(f"最終持倉: 總 {final_total} 倉 (DCA {final_dca} + AI {final_ai}) | 其中 2x 槓桿: {final_2x} 倉")
    print("=" * 110)


def create_daily_timeline_chart(daily_summary: list, price_df: pd.DataFrame, save_path: str, leverage_periods: list = None):
    """產生每日操作時間線圖表：價格走勢+買賣點、總倉數時序"""
    if not daily_summary:
        return
    
    summary_df = pd.DataFrame(daily_summary)
    summary_df.set_index('date', inplace=True)
    
    fig, axes = plt.subplots(2, 1, figsize=(16, 10), gridspec_kw={'height_ratios': [3, 1]})
    
    # 1. 價格走勢 + AI/DCA 買賣點標記 (不顯示信心度)
    ax1 = axes[0]
    
    # 標示 2x 槓桿期間 (背景色)
    if leverage_periods:
        for idx, (start_dt, end_dt) in enumerate(leverage_periods):
            ax1.axvspan(start_dt, end_dt, alpha=0.15, color='red', 
                       label='2x Leverage Period' if idx == 0 else '')
    
    ax1.plot(price_df.index, price_df['Close'], color='black', linewidth=1, label='^TWII')
    
    # AI BUY - 區分 1x 和 2x
    buy_mask = summary_df['ai_action'] == 'BUY'
    if buy_mask.any():
        buy_data = summary_df[buy_mask]
        if 'current_leverage' in buy_data.columns:
            buy_1x = buy_data[buy_data['current_leverage'] == 1.0]
            buy_2x = buy_data[buy_data['current_leverage'] > 1.0]
            if len(buy_1x) > 0:
                ax1.scatter(buy_1x.index, buy_1x['price'], marker='^', color='green', s=80, label='AI BUY (1x)', zorder=5)
            if len(buy_2x) > 0:
                ax1.scatter(buy_2x.index, buy_2x['price'], marker='^', color='red', s=100, label='AI BUY (2x)', zorder=6)
        else:
            ax1.scatter(buy_data.index, buy_data['price'], marker='^', color='green', s=80, label='AI BUY', zorder=5)
    
    # AI SELL
    sell_mask = summary_df['ai_action'] == 'SELL'
    if sell_mask.any():
        sell_dates = summary_df[sell_mask].index
        sell_prices = summary_df[sell_mask]['price']
        ax1.scatter(sell_dates, sell_prices, marker='v', color='purple', s=80, label='AI SELL', zorder=5)
    
    # DCA BUY (dca_position_count 增加時)
    dca_positions = summary_df['dca_position_count'].values
    dca_increase = [False] + [dca_positions[i] > dca_positions[i-1] for i in range(1, len(dca_positions))]
    dca_buy_dates = summary_df.index[dca_increase]
    dca_buy_prices = summary_df.loc[dca_buy_dates, 'price']
    if len(dca_buy_dates) > 0:
        ax1.scatter(dca_buy_dates, dca_buy_prices, marker='o', color='blue', s=60, label='DCA BUY', zorder=4, alpha=0.7)
    
    title_suffix = " (with 2x Leverage on Drawdown)" if leverage_periods else ""
    ax1.set_title(f'AI & DCA Trading Signals{title_suffix}', fontsize=14)
    ax1.set_ylabel('Price')
    ax1.legend(loc='upper left', fontsize=8)
    ax1.grid(True, alpha=0.3)
    
    # 2. 倉數時序圖 (堆疊區域圖: DCA + AI)
    ax2 = axes[1]
    
    # 標示 2x 槓桿期間 (背景色)
    if leverage_periods:
        for idx, (start_dt, end_dt) in enumerate(leverage_periods):
            ax2.axvspan(start_dt, end_dt, alpha=0.15, color='red')
    
    dates = summary_df.index
    dca_pos = summary_df['dca_position_count'].values
    ai_pos = summary_df['ai_position_count'].values
    total_pos = summary_df['total_position_count'].values
    
    # 堆疊區域圖
    ax2.fill_between(dates, 0, dca_pos, alpha=0.6, color='blue', label='DCA 倉')
    ax2.fill_between(dates, dca_pos, total_pos, alpha=0.6, color='green', label='AI 倉')
    ax2.plot(dates, total_pos, color='black', linewidth=1.5, label='總倉數')
    
    # 如果有 2x 倉位資訊，也顯示
    if 'positions_2x' in summary_df.columns:
        pos_2x = summary_df['positions_2x'].values
        ax2.plot(dates, pos_2x, color='red', linewidth=1.5, linestyle='--', label='2x 倉數')
    
    # 標示最終倉數
    final_total = total_pos[-1]
    final_dca = dca_pos[-1]
    final_ai = ai_pos[-1]
    final_2x = summary_df['positions_2x'].iloc[-1] if 'positions_2x' in summary_df.columns else 0
    
    label_text = f'總{final_total}倉\n(DCA{final_dca}+AI{final_ai})'
    if final_2x > 0:
        label_text += f'\n[2x:{final_2x}]'
    
    ax2.annotate(label_text, 
                (dates[-1], final_total), 
                textcoords="offset points", xytext=(10, 0), 
                ha='left', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))
    
    ax2.set_ylabel('Position Count (倉數)')
    ax2.set_xlabel('Date')
    ax2.legend(loc='upper left')
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim(0, max(total_pos) * 1.15)
    
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"[Output] Daily Timeline Chart: {save_path}")
    plt.close()


if __name__ == "__main__":
    main()
