# -*- coding: utf-8 -*-
"""
================================================================================
V5 無濾網回測腳本 (對稱獎勵版本 - No Filter)
================================================================================
測試 V5 模型的交易績效。V5 Buy Agent 使用對稱獎勵結構訓練，無唐其安濾網限制。

V5 特點:
- Buy Agent 對稱獎勵: 買對/正確迴避 +1.0, 買錯/錯過 0.0
- Sell Agent 與 V4 相同

作者：Phil Liang (Generated by Gemini)
日期：2025-12-27
================================================================================
"""

import os
import sys
import pickle
import argparse
from datetime import datetime

# Windows UTF-8 設定
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from stable_baselines3 import PPO

# 中文字型設定
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

# =============================================================================
# 設定
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
V5_MODELS_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v5')
RESULTS_PATH = os.path.join(PROJECT_PATH, 'results_backtest_v5_no_filter')
CACHE_DIR = os.path.join(PROJECT_PATH, 'data', 'processed')

DEFAULT_START_DATE = '2017-10-16'  # V6.02: 驗證集起始日
DEFAULT_END_DATE = '2023-10-15'    # V6.02: 驗證集結束日
INITIAL_CAPITAL = 1_000_000


def parse_args():
    """解析命令列參數"""
    parser = argparse.ArgumentParser(
        description='V5 無濾網回測腳本 - 對稱獎勵版本',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
使用範例:
  python backtest_v5_no_filter.py                           # 使用預設日期 (2017-10-16 ~ 2023-10-15)
  python backtest_v5_no_filter.py --start 2020-01-01        # 從 2020-01-01 至 2023-10-15
  python backtest_v5_no_filter.py --start 2018-01-01 --end 2022-12-31  # 指定完整日期範圍
        '''
    )
    parser.add_argument(
        '--start', 
        type=str, 
        default=DEFAULT_START_DATE,
        help=f'回測開始日期 (YYYY-MM-DD 格式，預設: {DEFAULT_START_DATE})'
    )
    parser.add_argument(
        '--end', 
        type=str, 
        default=DEFAULT_END_DATE,
        help='回測結束日期 (YYYY-MM-DD 格式，預設: 最新資料)'
    )
    parser.add_argument('--sell-threshold', type=float, default=0.6, help='Confidence threshold for sell signals')
    parser.add_argument('--buy-consensus-threshold', type=float, default=0.5, help='Buy confidence threshold to veto sell signals')
    return parser.parse_args()


# =============================================================================
# V5 回測器
# =============================================================================
class V5Backtester:
    """
    V5 回測器：無濾網限制
    """
    def __init__(self, buy_model, sell_model, initial_capital=1_000_000, 
                 sell_threshold=0.6, buy_consensus_threshold=0.5):
        self.buy_model = buy_model
        self.sell_model = sell_model
        self.initial_capital = initial_capital
        self.sell_threshold = sell_threshold
        self.buy_consensus_threshold = buy_consensus_threshold
        self.trades = []
        self.equity_curve = []
        self.buy_signals = []
        self.sell_signals = []
        self.daily_confidence = []
    
    def run(self, df: pd.DataFrame, feature_cols: list) -> dict:
        """執行回測"""
        capital = self.initial_capital
        position = None
        
        features = df[feature_cols].values.astype(np.float32)
        close_prices = df['Close'].values
        dates = df.index
            
        print(f"[Backtest] 回測期間: {dates[0].strftime('%Y-%m-%d')} ~ {dates[-1].strftime('%Y-%m-%d')}")
        print(f"[Backtest] 資料筆數: {len(df)}")
        print(f"[Backtest] 初始資金: ${capital:,.0f}")
        print("[Backtest] 模式: V5 無濾網 (對稱獎勵)")
        
        for i in range(len(df)):
            date = dates[i]
            price = close_prices[i]
            
            # 記錄每日淨值
            if position is not None:
                current_value = capital + position['shares'] * price
            else:
                current_value = capital
            self.equity_curve.append({'date': date, 'value': current_value})
            
            # 處理 NaN
            obs = np.nan_to_num(features[i], nan=0.0, posinf=1.0, neginf=-1.0)
            
            # =================================================================
            # 持有中：檢查賣出
            # =================================================================
            if position is not None:
                hold_days = i - position['buy_idx']
                current_return = price / position['buy_price']
                
                sell_obs = np.concatenate([obs, [current_return]]).astype(np.float32).reshape(1, -1)
                action, _ = self.sell_model.predict(sell_obs, deterministic=True)
                
                sell_obs_tensor = self.sell_model.policy.obs_to_tensor(sell_obs)[0]
                sell_probs = self.sell_model.policy.get_distribution(sell_obs_tensor).distribution.probs.detach().cpu().numpy()[0]
                sell_confidence = float(sell_probs[1]) if action[0] == 1 else float(sell_probs[0])
                
                # 🔥 Agent Consensus Check: 取得 Buy Agent 對當前市場的信心
                # (即使目前是持有狀態，也要問 Buy Agent 怎麼看)
                buy_obs_check = obs.reshape(1, -1)
                buy_action_check, _ = self.buy_model.predict(buy_obs_check, deterministic=True)
                buy_check_tensor = self.buy_model.policy.obs_to_tensor(buy_obs_check)[0]
                buy_check_probs = self.buy_model.policy.get_distribution(buy_check_tensor).distribution.probs.detach().cpu().numpy()[0]
                # 取得 Buy Confidence (看漲機率)
                current_buy_conf = float(buy_check_probs[1]) if buy_action_check[0] == 1 else float(buy_check_probs[0])
                if buy_action_check[0] == 0: # 如果是看跌/觀望，信心要轉換嗎？不，我們需要的是「想買」的信心
                     # StableBaselines3 的 probs 是 [prob_0, prob_1]
                     # 如果 action 是 0 (WAIT), conf 是 prob_0. 我們需要 prob_1 (BUY機率) 來判斷多頭共識
                     current_buy_conf = float(buy_check_probs[1]) 

                self.daily_confidence.append({
                    'date': date, 'status': 'holding', 'price': price,
                    'buy_conf': current_buy_conf, 'sell_conf': sell_confidence,
                    'sell_action': 'SELL' if action[0] == 1 else 'HOLD',
                    'current_return': current_return
                })
                
                stop_loss = current_return < 0.92
                is_sell_signal = (action[0] == 1 and sell_confidence > self.sell_threshold)
                
                # Consensus Veto
                is_vetoed = False
                if is_sell_signal and not stop_loss:
                    # 🔥 只有當 Buy Agent 真心想買 (Action=1) 且信心夠高時，才否決賣出
                    if buy_action_check[0] == 1 and current_buy_conf > self.buy_consensus_threshold:
                        is_vetoed = True
                        # print(f"  🛑 [{date.strftime('%Y-%m-%d')}] Sell Vetoed! SellConf:{sell_confidence:.2f} BuyProb:{current_buy_conf:.2f}")

                should_sell = (is_sell_signal and not is_vetoed) or stop_loss
                
                if should_sell:
                    sell_value = position['shares'] * price
                    profit = sell_value - position['shares'] * position['buy_price']
                    capital += sell_value
                    
                    sell_reason = 'stop_loss' if stop_loss else 'ai_signal'
                    
                    self.trades.append({
                        'buy_date': position['buy_date'],
                        'buy_price': position['buy_price'],
                        'buy_confidence': position.get('buy_confidence', 0),
                        'sell_date': date,
                        'sell_price': price,
                        'sell_confidence': sell_confidence,
                        'sell_reason': sell_reason,
                        'return': current_return - 1,
                        'profit': profit,
                        'hold_days': hold_days
                    })
                    self.sell_signals.append((date, price, sell_confidence))
                    position = None
            
            # =================================================================
            # 空手：檢查買入 (無濾網)
            # =================================================================
            elif position is None:
                buy_obs = obs.reshape(1, -1)
                action, _ = self.buy_model.predict(buy_obs, deterministic=True)
                
                buy_obs_tensor = self.buy_model.policy.obs_to_tensor(buy_obs)[0]
                buy_probs = self.buy_model.policy.get_distribution(buy_obs_tensor).distribution.probs.detach().cpu().numpy()[0]
                buy_confidence = float(buy_probs[1]) if action[0] == 1 else float(buy_probs[0])
                
                ai_buy = action[0] == 1
                
                self.daily_confidence.append({
                    'date': date, 'status': 'idle', 'price': price,
                    'buy_conf': buy_confidence, 'sell_conf': None,
                    'buy_action': 'BUY' if ai_buy else 'WAIT',
                    'current_return': None
                })
                
                if ai_buy:
                    invest_amount = capital * 0.9
                    shares = int(invest_amount / price)
                    
                    if shares > 0:
                        cost = shares * price
                        capital -= cost
                        
                        position = {
                            'shares': shares,
                            'buy_price': price,
                            'buy_date': date,
                            'buy_idx': i,
                            'buy_confidence': buy_confidence
                        }
                        self.buy_signals.append((date, price, buy_confidence))
        
        return self._calculate_metrics(df)
    
    def _calculate_metrics(self, df: pd.DataFrame) -> dict:
        """計算績效指標"""
        if not self.equity_curve:
            return {}
        
        equity_df = pd.DataFrame(self.equity_curve)
        equity_df['date'] = pd.to_datetime(equity_df['date'])
        equity_df.set_index('date', inplace=True)
        
        initial = self.initial_capital
        final = equity_df['value'].iloc[-1]
        total_return = (final - initial) / initial
        
        days = (equity_df.index[-1] - equity_df.index[0]).days
        years = days / 365.0
        annualized_return = (1 + total_return) ** (1 / years) - 1 if years > 0 else 0
        
        daily_returns = equity_df['value'].pct_change().dropna()
        if len(daily_returns) > 0 and daily_returns.std() > 0:
            sharpe = (daily_returns.mean() * 252 - 0.02) / (daily_returns.std() * np.sqrt(252))
        else:
            sharpe = 0
        
        rolling_max = equity_df['value'].cummax()
        drawdown = (equity_df['value'] - rolling_max) / rolling_max
        max_drawdown = drawdown.min()
        
        if self.trades:
            wins = sum(1 for t in self.trades if t['return'] > 0)
            win_rate = wins / len(self.trades)
            avg_return = np.mean([t['return'] for t in self.trades])
            avg_hold_days = np.mean([t['hold_days'] for t in self.trades])
        else:
            win_rate = 0
            avg_return = 0
            avg_hold_days = 0
        
        return {
            'initial_capital': initial,
            'final_value': final,
            'total_return': total_return,
            'annualized_return': annualized_return,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_drawdown,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'avg_return': avg_return,
            'avg_hold_days': avg_hold_days,
            'equity_df': equity_df
        }


# =============================================================================
# 主程式
# =============================================================================
def main():
    args = parse_args()
    
    try:
        start_date = pd.Timestamp(args.start)
    except Exception as e:
        print(f"[Error] 無效的開始日期格式: {args.start}")
        sys.exit(1)
    
    end_date = None
    if args.end:
        try:
            end_date = pd.Timestamp(args.end)
        except Exception as e:
            print(f"[Error] 無效的結束日期格式: {args.end}")
            sys.exit(1)
        
        # [v6.02] 當結束日期比開始日期早時，自動使用今天的日期
        if end_date <= start_date:
            end_date = pd.Timestamp.now().normalize()
            print(f"[Notice] 預設結束日期早於開始日期，已自動調整為今天: {end_date.date()}")
    
    print("=" * 60)
    print("V5 無濾網回測 (對稱獎勵版本 - No Filter)")
    print("=" * 60)
    print(f"  📅 開始日期: {args.start}")
    print(f"  📅 結束日期: {args.end if args.end else '最新資料'}")
    print(f"  ⚙️ Sell Threshold: {args.sell_threshold}")
    print(f"  ⚙️ Buy Consensus Threshold: {args.buy_consensus_threshold}")
    
    os.makedirs(RESULTS_PATH, exist_ok=True)
    
    # =========================================================================
    # 載入模型
    # =========================================================================
    print("\n[Model] 載入 V5 模型...")
    buy_path = os.path.join(V5_MODELS_PATH, 'ppo_buy_twii_final.zip')
    sell_path = os.path.join(V5_MODELS_PATH, 'ppo_sell_twii_final.zip')
    
    if not os.path.exists(buy_path):
        print(f"[Error] 模型不存在: {buy_path}")
        print("請先執行 train_v5_models.py")
        sys.exit(1)
    
    buy_model = PPO.load(buy_path)
    sell_model = PPO.load(sell_path)
    print("  ✅ 模型載入成功")
    
    # =========================================================================
    # 載入/計算特徵資料
    # =========================================================================
    print("\n[Data] 準備回測資料...")
    import ptrl_hybrid_system as hybrid
    
    # [v6.0] LSTM 已移除，不再載入 LSTM 模型
    
    cache_path = os.path.join(CACHE_DIR, "_TWII_features.pkl")
    if os.path.exists(cache_path):
        print(f"  [Cache] 載入快取: {cache_path}")
        with open(cache_path, 'rb') as f:
            twii_full_df = pickle.load(f)
    else:
        print("  [Compute] Load ^TWII from local CSV...")
        twii_raw = hybrid._load_local_twii_data(start_date="2000-01-01")
        twii_full_df = hybrid.calculate_features(twii_raw, twii_raw, ticker="^TWII", use_cache=False)
    
    twii_backtest_df = twii_full_df[twii_full_df.index >= start_date]
    if end_date:
        twii_backtest_df = twii_backtest_df[twii_backtest_df.index <= end_date]
    
    if len(twii_backtest_df) == 0:
        print(f"[Error] 指定的日期範圍內沒有資料")
        sys.exit(1)
    
    print(f"  回測期間: {twii_backtest_df.index[0].strftime('%Y-%m-%d')} ~ {twii_backtest_df.index[-1].strftime('%Y-%m-%d')}")
    print(f"  資料筆數: {len(twii_backtest_df)}")
    
    # =========================================================================
    # 執行回測
    # =========================================================================
    print("\n[Backtest] 開始 V5 回測...")
    backtester = V5Backtester(
        buy_model, 
        sell_model, 
        INITIAL_CAPITAL,
        sell_threshold=args.sell_threshold,
        buy_consensus_threshold=args.buy_consensus_threshold
    )
    metrics = backtester.run(twii_backtest_df, hybrid.FEATURE_COLS)
    
    # =========================================================================
    # 計算 Benchmark
    # =========================================================================
    equity_df = metrics['equity_df']
    bench_slice = twii_full_df.loc[equity_df.index[0]:equity_df.index[-1]]['Close']
    bench_normalized = bench_slice / bench_slice.iloc[0] * INITIAL_CAPITAL
    
    bench_initial = INITIAL_CAPITAL
    bench_final = bench_normalized.iloc[-1]
    bench_total_return = (bench_final - bench_initial) / bench_initial
    
    days = (bench_slice.index[-1] - bench_slice.index[0]).days
    years = days / 365.0
    bench_annualized = (1 + bench_total_return) ** (1 / years) - 1 if years > 0 else 0
    
    bench_daily_returns = bench_normalized.pct_change().dropna()
    if len(bench_daily_returns) > 0 and bench_daily_returns.std() > 0:
        bench_sharpe = (bench_daily_returns.mean() * 252 - 0.02) / (bench_daily_returns.std() * np.sqrt(252))
    else:
        bench_sharpe = 0
    
    bench_rolling_max = bench_normalized.cummax()
    bench_drawdown = (bench_normalized - bench_rolling_max) / bench_rolling_max
    bench_max_dd = bench_drawdown.min()
    
    # =========================================================================
    # 印出績效
    # =========================================================================
    print("\n" + "=" * 70)
    print("Performance Comparison: V5 (對稱獎勵) vs Buy & Hold")
    print("=" * 70)
    print(f"{'Metric':<20} {'V5':<20} {'Buy & Hold':<20}")
    print("-" * 70)
    print(f"{'Initial Capital':<20} ${metrics['initial_capital']:>17,.0f} ${bench_initial:>17,.0f}")
    print(f"{'Final Value':<20} ${metrics['final_value']:>17,.0f} ${bench_final:>17,.0f}")
    print(f"{'Total Return':<20} {metrics['total_return']*100:>17.2f}% {bench_total_return*100:>17.2f}%")
    print(f"{'Annualized Return':<20} {metrics['annualized_return']*100:>17.2f}% {bench_annualized*100:>17.2f}%")
    print(f"{'Sharpe Ratio':<20} {metrics['sharpe_ratio']:>18.2f} {bench_sharpe:>18.2f}")
    print(f"{'Max Drawdown':<20} {metrics['max_drawdown']*100:>17.2f}% {bench_max_dd*100:>17.2f}%")
    print("-" * 70)
    print(f"{'Trades':<20} {metrics['total_trades']:>18}")
    print(f"{'Win Rate':<20} {metrics['win_rate']*100:>17.1f}%")
    print(f"{'Avg Return/Trade':<20} {metrics['avg_return']*100:>17.2f}%")
    print(f"{'Avg Hold Days':<20} {metrics['avg_hold_days']:>18.1f}")
    print("=" * 70)
    
    # =========================================================================
    # 視覺化
    # =========================================================================
    fig, axes = plt.subplots(2, 1, figsize=(14, 10))
    
    ax1 = axes[0]
    ax1.plot(equity_df.index, equity_df['value'], label='V5 (對稱獎勵)', color='blue', linewidth=2)
    ax1.plot(bench_normalized.index, bench_normalized.values, 
             label='^TWII Buy & Hold', color='gray', linewidth=1.5, alpha=0.7)
    
    date_range_str = f"{twii_backtest_df.index[0].strftime('%Y-%m-%d')} ~ {twii_backtest_df.index[-1].strftime('%Y-%m-%d')}"
    ax1.set_title(f'V5 (對稱獎勵) vs Buy & Hold ({date_range_str})', fontsize=14)
    ax1.set_ylabel('Portfolio Value ($)')
    ax1.legend(loc='upper left')
    ax1.grid(True, alpha=0.3)
    
    summary_text = (
        f"{'Metric':<12} {'V5':>12} {'B&H':>12}\n"
        f"{'-'*38}\n"
        f"{'Final':.<12} ${metrics['final_value']/1e6:>10.2f}M ${bench_final/1e6:>10.2f}M\n"
        f"{'Return':.<12} {metrics['total_return']*100:>11.1f}% {bench_total_return*100:>11.1f}%\n"
        f"{'Annual':.<12} {metrics['annualized_return']*100:>11.1f}% {bench_annualized*100:>11.1f}%\n"
        f"{'Sharpe':.<12} {metrics['sharpe_ratio']:>12.2f} {bench_sharpe:>12.2f}\n"
        f"{'Max DD':.<12} {metrics['max_drawdown']*100:>11.1f}% {bench_max_dd*100:>11.1f}%\n"
        f"{'-'*38}\n"
        f"{'Trades':.<12} {metrics['total_trades']:>12}\n"
        f"{'Win Rate':.<12} {metrics['win_rate']*100:>11.1f}%"
    )
    
    props = dict(boxstyle='round,pad=0.5', facecolor='white', alpha=0.9, edgecolor='gray')
    ax1.text(0.98, 0.03, summary_text, transform=ax1.transAxes, fontsize=9,
             verticalalignment='bottom', horizontalalignment='right',
             bbox=props, family='monospace')
    
    ax2 = axes[1]
    price_slice = twii_backtest_df['Close']
    ax2.plot(price_slice.index, price_slice.values, label='^TWII Close', color='black', linewidth=1)
    
    if backtester.buy_signals:
        buy_dates, buy_prices, buy_confs = zip(*backtester.buy_signals)
        ax2.scatter(buy_dates, buy_prices, marker='^', color='red', s=100, label='Buy', zorder=5)
        for dt, pr, conf in backtester.buy_signals:
            ax2.annotate(f'{conf:.0%}', (dt, pr), textcoords="offset points", 
                        xytext=(0, 10), ha='center', fontsize=7, color='red', fontweight='bold')
    
    if backtester.sell_signals:
        sell_dates, sell_prices, sell_confs = zip(*backtester.sell_signals)
        ax2.scatter(sell_dates, sell_prices, marker='v', color='green', s=100, label='Sell', zorder=5)
        for dt, pr, conf in backtester.sell_signals:
            ax2.annotate(f'{conf:.0%}', (dt, pr), textcoords="offset points", 
                        xytext=(0, -15), ha='center', fontsize=7, color='green', fontweight='bold')
    
    ax2.set_title('Trade Signals with Confidence (V5)', fontsize=14)
    ax2.set_ylabel('Price')
    ax2.set_xlabel('Date')
    ax2.legend(loc='upper left')
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    start_str = twii_backtest_df.index[0].strftime('%Y%m%d')
    end_str = twii_backtest_df.index[-1].strftime('%Y%m%d')
    save_path = os.path.join(RESULTS_PATH, f'backtest_v5_{start_str}_{end_str}.png')
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"\n[Output] Chart saved: {save_path}")
    plt.close()
    
    # =========================================================================
    # 儲存檔案
    # =========================================================================
    metrics_df = pd.DataFrame({
        'Metric': ['Initial_Capital', 'Final_Value', 'Total_Return_Pct', 'Annualized_Return_Pct', 
                   'Sharpe_Ratio', 'Max_Drawdown_Pct', 'Trades', 'Win_Rate_Pct', 'Avg_Return_Pct', 'Avg_Hold_Days'],
        'V5': [metrics['initial_capital'], metrics['final_value'], metrics['total_return']*100,
               metrics['annualized_return']*100, metrics['sharpe_ratio'], metrics['max_drawdown']*100,
               metrics['total_trades'], metrics['win_rate']*100, metrics['avg_return']*100, metrics['avg_hold_days']],
        'Buy_Hold': [bench_initial, bench_final, bench_total_return*100, bench_annualized*100,
                     bench_sharpe, bench_max_dd*100, 'N/A', 'N/A', 'N/A', 'N/A']
    })
    metrics_path = os.path.join(RESULTS_PATH, f'metrics_v5_{start_str}_{end_str}.csv')
    metrics_df.to_csv(metrics_path, index=False, encoding='utf-8-sig')
    print(f"[Output] Metrics CSV: {metrics_path}")
    
    if backtester.trades:
        trades_df = pd.DataFrame(backtester.trades)
        trades_path = os.path.join(RESULTS_PATH, f'trades_v5_{start_str}_{end_str}.csv')
        trades_df.to_csv(trades_path, index=False)
        print(f"[Output] 交易明細: {trades_path}")
        
        print("\n[Trades] 最近 5 筆交易:")
        print(trades_df.tail().to_string(index=False))
    
    if backtester.daily_confidence:
        conf_df = pd.DataFrame(backtester.daily_confidence)
        conf_path = os.path.join(RESULTS_PATH, f'daily_confidence_v5_{start_str}_{end_str}.csv')
        conf_df.to_csv(conf_path, index=False)
        print(f"[Output] 每日信心度: {conf_path}")
    
    print("\n" + "=" * 60)
    print("✅ V5 回測完成！")
    print("=" * 60)


if __name__ == "__main__":
    main()
