# -*- coding: utf-8 -*-
"""
================================================================================
V5 Strategy 3 Comparison: Strat 1 vs 2 vs 3 vs Benchmarks
================================================================================
這個腳本整合了以下策略進行比較回測：

1. **Strategy 1 (Leveraged Shared Pool)**:
   - Shared Pool + Dynamic Chunk (按月剩餘資金分配)
   - Dynamic Filter (MA120 Regime + Donchian) + KD Filter
   - **2x Leverage** on Drawdown > 8% (DCA & AI positions)
   - AI Sell Management + Stop Loss

2. **Strategy 2 (Shared Pool)**:
   - Shared Pool + Dynamic Chunk
   - Dynamic Filter (MA120 Regime + Donchian)
   - NO Leverage, NO KD Filter (Default)
   - AI Sell Management + Stop Loss

3. **Strategy 3 (Yearly Lump Hybrid)**: <-- New Focus
   - **Yearly Lump Sum**: 年初一次性買入當年度資金。
   - **AI Managed Exit**: 該一次性倉位由 AI Sell Agent 監控與賣出。
   - **AI Managed Re-entry**: 賣出後資金回池，由 AI Buy Agent (Shared Pool Logic + KD) 決定買回時機。
   - **2x Leverage** on Drawdown > 8%

4. **Pure DCA**: 每月固定金額買入 (Benchmark)。
5. **Yearly Lump Sum**: 每年年初固定買入 (Benchmark - Passively Held)。

作者：Phil Liang (Generated by Gemini)
日期：2026-01-10
================================================================================
"""

import os
import sys
import argparse
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from stable_baselines3 import PPO

# Windows UTF-8 設定
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# 中文字型設定
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

# =============================================================================
# 設定
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
V5_MODELS_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v5')
RESULTS_PATH = os.path.join(PROJECT_PATH, 'results_backtest_v5_strat3_comparison')
CACHE_DIR = os.path.join(PROJECT_PATH, 'data', 'processed')

DEFAULT_START_DATE = '2017-10-16'
DEFAULT_END_DATE = '2023-10-15'
YEARLY_CAPITAL = 600_000  
MONTHLY_DCA_BENCHMARK = 50_000

def parse_args():
    parser = argparse.ArgumentParser(
        description='V5 Strategy 3 Comparison Backtest',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument('--start', type=str, default=DEFAULT_START_DATE)
    parser.add_argument('--end', type=str, default=DEFAULT_END_DATE)
    parser.add_argument('--sell-threshold', type=float, default=0.6, help='Confidence threshold for sell signals')
    parser.add_argument('--buy-consensus-threshold', type=float, default=0.5, help='Buy confidence threshold to veto sell signals')
    parser.add_argument('--kd-threshold', type=float, default=90, help='KD threshold for AI buy filter (Strat 1/3)')
    return parser.parse_args()


# =============================================================================
# Strategy 1: Leveraged Shared Pool
# =============================================================================
class LeveragedSharedPoolBacktester:
    LEVERAGE_THRESHOLD = 0.08
    
    def __init__(self, buy_model, sell_model, yearly_capital=600_000,
                 dca_amount=50_000, sell_threshold=0.6, buy_consensus_threshold=0.5, kd_threshold=60):
        self.buy_model = buy_model
        self.sell_model = sell_model
        self.yearly_capital = yearly_capital
        self.dca_amount = dca_amount  # Initial Target
        self.sell_threshold = sell_threshold
        self.buy_consensus_threshold = buy_consensus_threshold
        self.kd_threshold = kd_threshold
        
        self.trades = []
        self.equity_curve = []
        self.dca_buy_signals = []      
        self.ai_buy_signals = []       
        self.ai_sell_signals = []
        self.daily_action_summary = []
        self.leverage_events = []
        self.leverage_periods = []
        self.total_invested = 0

    def run(self, df: pd.DataFrame, feature_cols: list) -> dict:
        features = df[feature_cols].values.astype(np.float32)
        close_prices = df['Close'].values
        dates = df.index
        
        if 'Signal_Buy_Filter' not in df.columns:
            donchian_signals = np.ones(len(df), dtype=bool)
        else:
            donchian_signals = df['Signal_Buy_Filter'].values.astype(bool)
        
        ma120_values = df['MA120'].values
        
        yearly_pool = 0
        dca_positions = []
        ai_positions = []
        
        current_year = None
        last_dca_month = None
        dynamic_chunk_amount = self.dca_amount
        
        leveraged_mode = False
        leverage_trigger_price = 0
        peak_price = close_prices[0]
        current_leverage_start = None
        
        bear_counter = 0     
        current_regime = 'BULL'
        
        for i in range(len(df)):
            date = dates[i]
            price = close_prices[i]
            year = date.year
            month = date.month
            
            # --- Leverage Logic ---
            if not leveraged_mode:
                peak_price = max(peak_price, price)
                if price < peak_price * (1 - self.LEVERAGE_THRESHOLD):
                    leveraged_mode = True
                    leverage_trigger_price = price
                    current_leverage_start = date
                    self.leverage_events.append({'date': date, 'event': 'START', 'price': price})
            else:
                if price >= leverage_trigger_price:
                    leveraged_mode = False
                    self.leverage_events.append({'date': date, 'event': 'END', 'price': price})
                    self.leverage_periods.append((current_leverage_start, date))
                    peak_price = price
                    current_leverage_start = None
            
            current_leverage = 2.0 if leveraged_mode else 1.0
            
            # --- Regime Logic ---
            ma120 = ma120_values[i]
            if not np.isnan(ma120):
                if price < ma120: bear_counter += 1
                else: bear_counter = 0
                
                if current_regime == 'BULL' and bear_counter >= 3: current_regime = 'BEAR'
                elif current_regime == 'BEAR' and price >= ma120: current_regime = 'BULL'
            
            pass_dynamic_filter = True
            if current_regime == 'BEAR' and not donchian_signals[i]:
                pass_dynamic_filter = False
            
            # --- Yearly Injection ---
            if current_year != year:
                current_year = year
                last_dca_month = None
                yearly_pool += self.yearly_capital
                self.total_invested += self.yearly_capital
                remaining_months = 13 - month
                dynamic_chunk_amount = yearly_pool / remaining_months if remaining_months > 0 else yearly_pool

            # --- Recalculate Monthly ---
            if last_dca_month != month:
                remaining_months = 13 - month
                dynamic_chunk_amount = yearly_pool / remaining_months if remaining_months > 0 else yearly_pool
                dynamic_chunk_amount = max(dynamic_chunk_amount, 10000)

            # --- DCA Buying ---
            day_dca_shares = 0
            if last_dca_month != month:
                last_dca_month = month
                fund = min(dynamic_chunk_amount, yearly_pool)
                if fund > price:
                    yearly_pool -= fund
                    shares = int(fund / price)
                    cost = shares * price
                    yearly_pool += (fund - cost)
                    dca_positions.append({'shares': shares, 'buy_price': price, 'buy_idx': i, 'cost': cost, 'leverage': current_leverage})
                    day_dca_shares = shares
                    self.dca_buy_signals.append((date, price, shares, current_leverage))
            
            # --- AI Logic ---
            obs = np.nan_to_num(features[i], nan=0.0, posinf=1.0, neginf=-1.0)
            day_action = 'HOLD'
            day_sold_count = 0
            
            current_obs = obs.reshape(1, -1)
            buy_action_pred, _ = self.buy_model.predict(current_obs, deterministic=True)
            # Conf calculation omitted for brevity if not strictly needed for logic, but kept for consistency
            buy_probs = self.buy_model.policy.get_distribution(self.buy_model.policy.obs_to_tensor(current_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
            current_buy_conf = float(buy_probs[1]) if buy_action_pred[0] == 1 else float(buy_probs[0])

            # AI Sell
            stop_loss_triggered_today = False
            for idx in range(len(ai_positions) - 1, -1, -1):
                pos = ai_positions[idx]
                hold_days = i - pos['buy_idx']
                base_return = price / pos['buy_price']
                leveraged_return = 1 + (base_return - 1) * pos['leverage']
                
                sell_obs = np.concatenate([obs, [leveraged_return]]).astype(np.float32).reshape(1, -1)
                action, _ = self.sell_model.predict(sell_obs, deterministic=True)
                sell_probs = self.sell_model.policy.get_distribution(self.sell_model.policy.obs_to_tensor(sell_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
                sell_conf = float(sell_probs[1]) if action[0] == 1 else float(sell_probs[0])
                
                is_stop_loss = leveraged_return < 0.92
                is_sell_signal = (action[0] == 1 and sell_conf > self.sell_threshold)
                
                is_consensus_hold = False
                if is_sell_signal and not is_stop_loss:
                    if buy_action_pred[0] == 1 and current_buy_conf > self.buy_consensus_threshold:
                        is_consensus_hold = True
                
                if (is_sell_signal and not is_consensus_hold) or is_stop_loss:
                    leveraged_value = pos['cost'] * leveraged_return
                    profit = leveraged_value - pos['cost']
                    yearly_pool += leveraged_value
                    if is_stop_loss: stop_loss_triggered_today = True
                    
                    self.trades.append({'type': 'AI_S1', 'return': leveraged_return - 1, 'profit': profit, 'hold_days': hold_days})
                    self.ai_sell_signals.append({'date': date, 'price': price})
                    ai_positions.pop(idx)
                    day_action = 'SELL'
                    day_sold_count += 1
            
            # DCA Stop Loss
            if stop_loss_triggered_today and dca_positions:
                for dca_pos in dca_positions:
                    base_ret = price / dca_pos['buy_price']
                    lev_ret = 1 + (base_ret - 1) * dca_pos['leverage']
                    val = dca_pos['cost'] * lev_ret
                    profit = val - dca_pos['cost']
                    yearly_pool += val
                    self.trades.append({'type': 'DCA_STOPLOSS_S1', 'return': lev_ret - 1, 'profit': profit})
                dca_positions.clear()

            # AI Buy
            if yearly_pool >= dynamic_chunk_amount and dynamic_chunk_amount > price:
                if buy_action_pred[0] == 1:
                    current_k = df['K_raw'].values[i]
                    if pass_dynamic_filter and current_k < self.kd_threshold:
                        fund = min(dynamic_chunk_amount, yearly_pool)
                        if fund > price:
                            yearly_pool -= fund
                            shares = int(fund / price)
                            cost = shares * price
                            yearly_pool += (fund - cost)
                            ai_positions.append({'shares': shares, 'buy_price': price, 'buy_idx': i, 'cost': cost, 'leverage': current_leverage})
                            self.ai_buy_signals.append({'date': date, 'price': price, 'type': 'AI_BUY', 'leverage': current_leverage})
                            day_action = 'BUY'

            # Value Calc
            dca_val = sum(p['cost'] * (1 + (price / p['buy_price'] - 1) * p['leverage']) for p in dca_positions)
            ai_val = sum(p['cost'] * (1 + (price / p['buy_price'] - 1) * p['leverage']) for p in ai_positions)
            self.equity_curve.append({'date': date, 'value': dca_val + ai_val + yearly_pool})
            
            self.daily_action_summary.append({
                'date': date, 'ai_action': day_action, 'price': price, 
                'dca_action': 'BUY' if day_dca_shares > 0 else 'WAIT',
                'leverage': current_leverage
            })
            
        if leveraged_mode and current_leverage_start:
             self.leverage_periods.append((current_leverage_start, dates[-1]))
             
        return self._calculate_metrics()

    def _calculate_metrics(self) -> dict:
        if not self.equity_curve: return {}
        equity_df = pd.DataFrame(self.equity_curve).set_index('date')
        final = equity_df['value'].iloc[-1]
        total_return = (final - self.total_invested) / self.total_invested if self.total_invested > 0 else 0
        days = (equity_df.index[-1] - equity_df.index[0]).days
        annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
        daily_ret = equity_df['value'].pct_change().fillna(0)
        sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
        max_dd = ((equity_df['value'] - equity_df['value'].cummax()) / equity_df['value'].cummax()).min()
        wins = sum(1 for t in self.trades if t['return'] > 0)
        win_rate = wins / len(self.trades) if self.trades else 0
        
        return {
            'total_invested': self.total_invested,
            'final_value': final,
            'total_return': total_return,
            'annualized_return': annualized,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_dd,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'equity_df': equity_df,
            'dca_buys': len(self.dca_buy_signals),
            'ai_buys': len(self.ai_buy_signals),
            'leverage_periods': self.leverage_periods
        }


# =============================================================================
# Strategy 2: Shared Pool (No Leverage)
# =============================================================================
class SharedPoolBacktester:
    def __init__(self, buy_model, sell_model, yearly_capital=600_000, 
                 dca_amount=50_000, sell_threshold=0.6, buy_consensus_threshold=0.5):
        self.buy_model = buy_model
        self.sell_model = sell_model
        self.yearly_capital = yearly_capital
        self.dca_amount = dca_amount
        self.sell_threshold = sell_threshold
        self.buy_consensus_threshold = buy_consensus_threshold
        
        self.trades = []
        self.equity_curve = []
        self.dca_buy_signals = []      
        self.ai_buy_signals = []       
        self.ai_sell_signals = []
        self.total_invested = 0

    def run(self, df: pd.DataFrame, feature_cols: list) -> dict:
        features = df[feature_cols].values.astype(np.float32)
        close_prices = df['Close'].values
        dates = df.index
        
        if 'Signal_Buy_Filter' not in df.columns:
            donchian_signals = np.ones(len(df), dtype=bool)
        else:
            donchian_signals = df['Signal_Buy_Filter'].values.astype(bool)
        
        ma120_values = df['MA120'].values
        
        yearly_pool = 0
        dca_positions = [] # Simplification: Just track shares/cost is enough for Strat 2, but following structure
        # Actually Strat 2 DCA logic was just accumulate shares.
        
        dca_shares = 0
        ai_positions = []
        
        current_year = None
        last_dca_month = None
        dynamic_chunk_amount = self.dca_amount
        
        bear_counter = 0     
        current_regime = 'BULL'
        
        for i in range(len(df)):
            date = dates[i]
            price = close_prices[i]
            year = date.year
            month = date.month
            
            ma120 = ma120_values[i]
            if not np.isnan(ma120):
                if price < ma120: bear_counter += 1
                else: bear_counter = 0
                if current_regime == 'BULL' and bear_counter >= 3: current_regime = 'BEAR'
                elif current_regime == 'BEAR' and price >= ma120: current_regime = 'BULL'
            
            pass_dynamic_filter = True
            if current_regime == 'BEAR' and not donchian_signals[i]:
                pass_dynamic_filter = False
            
            if current_year != year:
                current_year = year
                last_dca_month = None
                yearly_pool += self.yearly_capital
                self.total_invested += self.yearly_capital
                remaining_months = 13 - month
                dynamic_chunk_amount = yearly_pool / remaining_months if remaining_months > 0 else yearly_pool

            if last_dca_month != month:
                remaining_months = 13 - month
                dynamic_chunk_amount = yearly_pool / remaining_months if remaining_months > 0 else yearly_pool
                dynamic_chunk_amount = max(dynamic_chunk_amount, 10000)

            # DCA
            if last_dca_month != month:
                last_dca_month = month
                fund = min(dynamic_chunk_amount, yearly_pool)
                if fund > price:
                    yearly_pool -= fund
                    shares = int(fund / price)
                    cost = shares * price
                    yearly_pool += (fund - cost)
                    dca_shares += shares
                    self.dca_buy_signals.append((date, price, shares))
            
            # AI
            obs = np.nan_to_num(features[i], nan=0.0, posinf=1.0, neginf=-1.0)
            current_obs = obs.reshape(1, -1)
            buy_action_pred, _ = self.buy_model.predict(current_obs, deterministic=True)
            buy_probs = self.buy_model.policy.get_distribution(self.buy_model.policy.obs_to_tensor(current_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
            current_buy_conf = float(buy_probs[1]) if buy_action_pred[0] == 1 else float(buy_probs[0])
            
            for idx in range(len(ai_positions) - 1, -1, -1):
                pos = ai_positions[idx]
                current_return = price / pos['buy_price']
                sell_obs = np.concatenate([obs, [current_return]]).astype(np.float32).reshape(1, -1)
                action, _ = self.sell_model.predict(sell_obs, deterministic=True)
                sell_probs = self.sell_model.policy.get_distribution(self.sell_model.policy.obs_to_tensor(sell_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
                sell_conf = float(sell_probs[1]) if action[0] == 1 else float(sell_probs[0])
                
                is_stop_loss = current_return < 0.92
                is_sell_signal = (action[0] == 1 and sell_conf > self.sell_threshold)
                
                is_consensus_hold = False
                if is_sell_signal and not is_stop_loss:
                    if buy_action_pred[0] == 1 and current_buy_conf > self.buy_consensus_threshold:
                        is_consensus_hold = True
                
                if (is_sell_signal and not is_consensus_hold) or is_stop_loss:
                    vals = pos['shares'] * price
                    profit = vals - pos['cost']
                    yearly_pool += vals
                    self.trades.append({'type': 'AI_S2', 'return': current_return - 1, 'profit': profit})
                    self.ai_sell_signals.append({'date': date, 'price': price})
                    ai_positions.pop(idx)
                    
            if yearly_pool >= dynamic_chunk_amount and dynamic_chunk_amount > price:
                if buy_action_pred[0] == 1 and pass_dynamic_filter:
                    fund = min(dynamic_chunk_amount, yearly_pool)
                    if fund > price:
                        yearly_pool -= fund
                        shares = int(fund / price)
                        cost = shares * price
                        yearly_pool += (fund - cost)
                        ai_positions.append({'shares': shares, 'buy_price': price, 'buy_idx': i, 'cost': cost})
                        self.ai_buy_signals.append({'date': date, 'price': price})

            dca_val = dca_shares * price
            ai_val = sum(p['shares'] * price for p in ai_positions)
            self.equity_curve.append({'date': date, 'value': dca_val + ai_val + yearly_pool})
            
        return self._calculate_metrics()

    def _calculate_metrics(self) -> dict:
        if not self.equity_curve: return {}
        equity_df = pd.DataFrame(self.equity_curve).set_index('date')
        final = equity_df['value'].iloc[-1]
        total_return = (final - self.total_invested) / self.total_invested if self.total_invested > 0 else 0
        days = (equity_df.index[-1] - equity_df.index[0]).days
        annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
        daily_ret = equity_df['value'].pct_change().fillna(0)
        sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
        max_dd = ((equity_df['value'] - equity_df['value'].cummax()) / equity_df['value'].cummax()).min()
        wins = sum(1 for t in self.trades if t['return'] > 0)
        win_rate = wins / len(self.trades) if self.trades else 0
        
        return {
            'total_invested': self.total_invested,
            'final_value': final,
            'total_return': total_return,
            'annualized_return': annualized,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_dd,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'equity_df': equity_df,
            'dca_buys': len(self.dca_buy_signals),
            'ai_buys': len(self.ai_buy_signals)
        }


# =============================================================================
# Strategy 3: Yearly Lump Sum + AI Hybrid
# =============================================================================
class YearlyLumpAIBacktester:
    LEVERAGE_THRESHOLD = 0.08
    
    def __init__(self, buy_model, sell_model, yearly_capital=600_000,
                 sell_threshold=0.6, buy_consensus_threshold=0.5, kd_threshold=60):
        self.buy_model = buy_model
        self.sell_model = sell_model
        self.yearly_capital = yearly_capital
        self.sell_threshold = sell_threshold
        self.buy_consensus_threshold = buy_consensus_threshold
        self.kd_threshold = kd_threshold
        
        self.trades = []
        self.equity_curve = []
        self.ai_buy_signals = []       
        self.ai_sell_signals = []
        self.daily_action_summary = []
        self.leverage_events = []
        self.leverage_periods = []
        self.total_invested = 0
        
    def run(self, df: pd.DataFrame, feature_cols: list) -> dict:
        features = df[feature_cols].values.astype(np.float32)
        close_prices = df['Close'].values
        dates = df.index
        
        if 'Signal_Buy_Filter' not in df.columns:
            donchian_signals = np.ones(len(df), dtype=bool)
        else:
            donchian_signals = df['Signal_Buy_Filter'].values.astype(bool)
        
        ma120_values = df['MA120'].values
        
        yearly_pool = 0
        ai_positions = []
        
        current_year = None
        
        leveraged_mode = False
        leverage_trigger_price = 0
        peak_price = close_prices[0]
        current_leverage_start = None
        
        bear_counter = 0     
        current_regime = 'BULL'
        
        for i in range(len(df)):
            date = dates[i]
            price = close_prices[i]
            year = date.year
            month = date.month
            
            # Leverage Logic
            if not leveraged_mode:
                peak_price = max(peak_price, price)
                if price < peak_price * (1 - self.LEVERAGE_THRESHOLD):
                    leveraged_mode = True
                    leverage_trigger_price = price
                    current_leverage_start = date
                    self.leverage_events.append({'date': date, 'event': 'START', 'price': price})
            else:
                if price >= leverage_trigger_price:
                    leveraged_mode = False
                    self.leverage_events.append({'date': date, 'event': 'END', 'price': price})
                    self.leverage_periods.append((current_leverage_start, date))
                    peak_price = price
                    current_leverage_start = None
                    
            current_leverage = 2.0 if leveraged_mode else 1.0
            
            # Regime Logic
            ma120 = ma120_values[i]
            if not np.isnan(ma120):
                if price < ma120: bear_counter += 1
                else: bear_counter = 0
                if current_regime == 'BULL' and bear_counter >= 3: current_regime = 'BEAR'
                elif current_regime == 'BEAR' and price >= ma120: current_regime = 'BULL'
            
            pass_dynamic_filter = True
            is_bear_mode = (current_regime == 'BEAR')
            if is_bear_mode and not donchian_signals[i]:
                pass_dynamic_filter = False
            
            # Yearly Lump
            if current_year != year:
                current_year = year
                yearly_pool += self.yearly_capital
                self.total_invested += self.yearly_capital
                
                # Immediate Buy
                fund = yearly_pool 
                if fund > price:
                    shares = int(fund / price)
                    cost = shares * price
                    yearly_pool = (fund - cost)
                    
                    ai_positions.append({
                        'shares': shares, 'buy_price': price, 'buy_idx': i, 
                        'cost': cost, 'leverage': current_leverage, 'type': 'LUMP_SUM'
                    })
                    self.ai_buy_signals.append({
                        'date': date, 'price': price, 'type': 'LUMP_SUM', 'leverage': current_leverage
                    })
            
            # AI Check
            obs = np.nan_to_num(features[i], nan=0.0, posinf=1.0, neginf=-1.0)
            current_obs = obs.reshape(1, -1)
            buy_action_pred, _ = self.buy_model.predict(current_obs, deterministic=True)
            buy_probs = self.buy_model.policy.get_distribution(self.buy_model.policy.obs_to_tensor(current_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
            current_buy_conf = float(buy_probs[1]) if buy_action_pred[0] == 1 else float(buy_probs[0])
            
            day_action = 'HOLD'
            day_note = ''
            
            for idx in range(len(ai_positions) - 1, -1, -1):
                pos = ai_positions[idx]
                hold_days = i - pos['buy_idx']
                base_return = price / pos['buy_price']
                leveraged_return = 1 + (base_return - 1) * pos['leverage']
                
                sell_obs = np.concatenate([obs, [leveraged_return]]).astype(np.float32).reshape(1, -1)
                action, _ = self.sell_model.predict(sell_obs, deterministic=True)
                sell_probs = self.sell_model.policy.get_distribution(self.sell_model.policy.obs_to_tensor(sell_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
                sell_conf = float(sell_probs[1]) if action[0] == 1 else float(sell_probs[0])
                
                is_stop_loss = leveraged_return < 0.92
                is_sell_signal = (action[0] == 1 and sell_conf > self.sell_threshold)
                
                is_consensus_hold = False
                if is_sell_signal and not is_stop_loss:
                    if buy_action_pred[0] == 1 and current_buy_conf > self.buy_consensus_threshold:
                        is_consensus_hold = True
                
                if (is_sell_signal and not is_consensus_hold) or is_stop_loss:
                    leveraged_value = pos['cost'] * leveraged_return
                    profit = leveraged_value - pos['cost']
                    yearly_pool += leveraged_value
                    
                    self.trades.append({
                        'type': pos.get('type', 'AI_REENTRY'),
                        'return': leveraged_return - 1,
                        'profit': profit,
                        'hold_days': hold_days
                    })
                    self.ai_sell_signals.append({'date': date, 'price': price})
                    ai_positions.pop(idx)
                    day_action = 'SELL'
            
            # Re-entry Logic: Chunked (Dynamic)
            remaining_months = 13 - month
            dynamic_chunk_amount = yearly_pool / remaining_months if remaining_months > 0 else yearly_pool
            dynamic_chunk_amount = max(dynamic_chunk_amount, 10000)
            
            if yearly_pool >= dynamic_chunk_amount and dynamic_chunk_amount > price and buy_action_pred[0] == 1:
                current_k = df['K_raw'].values[i]
                if pass_dynamic_filter and current_k < self.kd_threshold:
                    fund = min(dynamic_chunk_amount, yearly_pool)
                    if fund > price:
                        yearly_pool -= fund
                        shares = int(fund / price)
                        cost = shares * price
                        yearly_pool += (fund - cost)
                        ai_positions.append({
                            'shares': shares, 'buy_price': price, 'buy_idx': i, 
                            'cost': cost, 'leverage': current_leverage, 'type': 'AI_REENTRY'
                        })
                        self.ai_buy_signals.append({'date': date, 'price': price, 'type': 'REENTRY', 'leverage': current_leverage})
                        day_action = 'BUY'
            
            ai_val = sum(p['cost'] * (1 + (price / p['buy_price'] - 1) * p['leverage']) for p in ai_positions)
            self.equity_curve.append({'date': date, 'value': ai_val + yearly_pool})
            
            self.daily_action_summary.append({
                'date': date, 'ai_action': day_action, 'price': price, 
                'leverage': current_leverage, 
                'pool_balance': yearly_pool
            })
        
        if leveraged_mode and current_leverage_start:
             self.leverage_periods.append((current_leverage_start, dates[-1]))

        return self._calculate_metrics()

    def _calculate_metrics(self) -> dict:
        if not self.equity_curve: return {}
        equity_df = pd.DataFrame(self.equity_curve).set_index('date')
        final = equity_df['value'].iloc[-1]
        total_return = (final - self.total_invested) / self.total_invested if self.total_invested > 0 else 0
        days = (equity_df.index[-1] - equity_df.index[0]).days
        annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
        daily_ret = equity_df['value'].pct_change().fillna(0)
        sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
        max_dd = ((equity_df['value'] - equity_df['value'].cummax()) / equity_df['value'].cummax()).min()
        wins = sum(1 for t in self.trades if t['return'] > 0)
        win_rate = wins / len(self.trades) if self.trades else 0
        
        return {
            'total_invested': self.total_invested,
            'final_value': final,
            'total_return': total_return,
            'annualized_return': annualized,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_dd,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'equity_df': equity_df,
            'leverage_periods': self.leverage_periods
        }

# =============================================================================
# Benchmarks
# =============================================================================
def calculate_pure_dca(df: pd.DataFrame, monthly_amount: float = 50_000):
    close_prices = df['Close'].values
    dates = df.index
    shares = 0
    total_invested = 0
    equity_curve = []
    last_month = None
    leftover_cash = 0 
    current_year = None
    
    for i in range(len(df)):
        date = dates[i]
        price = close_prices[i]
        year = date.year
        month = date.month
        
        if current_year != year:
            current_year = year
            leftover_cash = 0
            
        if last_month != month:
            last_month = month
            fund = monthly_amount
            shares_to_buy = int(fund / price)
            if shares_to_buy > 0:
                cost = shares_to_buy * price
                leftover_cash += (fund - cost)
                shares += shares_to_buy
                total_invested += cost
            else:
                leftover_cash += fund
            
            if month == 12:
                extra_shares = int(leftover_cash / price)
                if extra_shares > 0:
                    extra_cost = extra_shares * price
                    shares += extra_shares
                    total_invested += extra_cost
                    leftover_cash -= extra_cost
                
        equity_curve.append({'date': date, 'value': shares * price})
    
    equity_df = pd.DataFrame(equity_curve).set_index('date')
    final = equity_df['value'].iloc[-1]
    total_return = (final - total_invested) / total_invested if total_invested > 0 else 0
    days = (equity_df.index[-1] - equity_df.index[0]).days
    annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
    daily_ret = equity_df['value'].pct_change().fillna(0)
    sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
    max_dd = ((equity_df['value'] - equity_df['value'].cummax()) / equity_df['value'].cummax()).min()
    
    return {
        'total_invested': total_invested, 'final_value': final, 'total_return': total_return,
        'annualized_return': annualized, 'sharpe_ratio': sharpe, 'max_drawdown': max_dd, 'equity_df': equity_df
    }


def calculate_yearly_lumpsum(df: pd.DataFrame, yearly_amount: float = 600_000):
    close_prices = df['Close'].values
    dates = df.index
    shares = 0
    total_invested = 0
    equity_curve = []
    current_year = None
    
    for i in range(len(df)):
        date = dates[i]
        price = close_prices[i]
        year = date.year
        if current_year != year:
            current_year = year
            shares_to_buy = int(yearly_amount / price)
            if shares_to_buy > 0:
                shares += shares_to_buy
                total_invested += shares_to_buy * price
        equity_curve.append({'date': date, 'value': shares * price})
    
    equity_df = pd.DataFrame(equity_curve).set_index('date')
    final = equity_df['value'].iloc[-1]
    total_return = (final - total_invested) / total_invested if total_invested > 0 else 0
    days = (equity_df.index[-1] - equity_df.index[0]).days
    annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
    daily_ret = equity_df['value'].pct_change().fillna(0)
    sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
    max_dd = ((equity_df['value'] - equity_df['value'].cummax()) / equity_df['value'].cummax()).min()
    
    return {
        'total_invested': total_invested, 'final_value': final, 'total_return': total_return,
        'annualized_return': annualized, 'sharpe_ratio': sharpe, 'max_drawdown': max_dd, 'equity_df': equity_df
    }

# =============================================================================
# Main
# =============================================================================
def main():
    args = parse_args()
    start_date = pd.Timestamp(args.start)
    end_date = pd.Timestamp(args.end) if args.end else None
    if end_date and end_date < start_date:
        end_date = pd.Timestamp.now().normalize()

    os.makedirs(RESULTS_PATH, exist_ok=True)
    
    print("[Model] Loading V5 models...")
    buy_model = PPO.load(os.path.join(V5_MODELS_PATH, 'ppo_buy_twii_final.zip'))
    sell_model = PPO.load(os.path.join(V5_MODELS_PATH, 'ppo_sell_twii_final.zip'))
    
    import ptrl_hybrid_system as hybrid
    print("[Data] Loading & Calculating features...")
    twii_raw = hybrid._load_local_twii_data(start_date="2000-01-01")
    twii_df = hybrid.calculate_features(twii_raw, twii_raw, ticker="^TWII", use_cache=False)
    
    twii_backtest = twii_df[twii_df.index >= start_date]
    if end_date: twii_backtest = twii_backtest[twii_backtest.index <= end_date]
    
    if len(twii_backtest) == 0:
        print("[Error] No data.")
        return

    # --- Run Strategies ---
    print("\n[Run] Strategy 1: Leveraged Shared Pool (Dynamic + KD)...")
    bt1 = LeveragedSharedPoolBacktester(buy_model, sell_model, YEARLY_CAPITAL, 
                                        sell_threshold=args.sell_threshold, buy_consensus_threshold=args.buy_consensus_threshold, kd_threshold=args.kd_threshold)
    m1 = bt1.run(twii_backtest, hybrid.FEATURE_COLS)
    
    print("\n[Run] Strategy 2: Shared Pool (Dynamic Only)...")
    bt2 = SharedPoolBacktester(buy_model, sell_model, YEARLY_CAPITAL, 
                               sell_threshold=args.sell_threshold, buy_consensus_threshold=args.buy_consensus_threshold)
    m2 = bt2.run(twii_backtest, hybrid.FEATURE_COLS)
    
    print("\n[Run] Strategy 3: Yearly Lump Hybrid...")
    bt3 = YearlyLumpAIBacktester(buy_model, sell_model, YEARLY_CAPITAL, 
                                 sell_threshold=args.sell_threshold, buy_consensus_threshold=args.buy_consensus_threshold, kd_threshold=args.kd_threshold)
    m3 = bt3.run(twii_backtest, hybrid.FEATURE_COLS)
    
    print("\n[Run] Benchmarks (DCA & Lump)...")
    dca = calculate_pure_dca(twii_backtest, MONTHLY_DCA_BENCHMARK)
    lump = calculate_yearly_lumpsum(twii_backtest, YEARLY_CAPITAL)
    
    # --- Metrics Table ---
    metrics_df = pd.DataFrame({
        'Metric': ['Total_Invested', 'Final_Value', 'Total_Return_Pct', 'Annualized_Return_Pct', 'Sharpe_Ratio', 'Max_Drawdown_Pct', 'DCA_Buys', 'AI_Win_Rate_Pct'],
        'Strat1_Split': [m1['total_invested'], m1['final_value'], m1['total_return']*100, m1['annualized_return']*100, m1['sharpe_ratio'], m1['max_drawdown']*100, m1['dca_buys'], m1['win_rate']*100],
        'Strat2_Shared': [m2['total_invested'], m2['final_value'], m2['total_return']*100, m2['annualized_return']*100, m2['sharpe_ratio'], m2['max_drawdown']*100, m2['dca_buys'], m2['win_rate']*100],
        'Strat3_Hybrid_Lump': [m3['total_invested'], m3['final_value'], m3['total_return']*100, m3['annualized_return']*100, m3['sharpe_ratio'], m3['max_drawdown']*100, 'N/A', m3['win_rate']*100],
        'Pure_DCA': [dca['total_invested'], dca['final_value'], dca['total_return']*100, dca['annualized_return']*100, dca['sharpe_ratio'], dca['max_drawdown']*100, 'N/A', 'N/A'],
        'Yearly_Lump': [lump['total_invested'], lump['final_value'], lump['total_return']*100, lump['annualized_return']*100, lump['sharpe_ratio'], lump['max_drawdown']*100, 'N/A', 'N/A']
    })
    
    print("\n" + "=" * 120)
    print("Performance Comparison")
    print("=" * 120)
    print(metrics_df.to_string(index=False, float_format=lambda x: f"{x:.2f}"))
    
    start_str = start_date.strftime('%Y%m%d')
    end_str = end_date.strftime('%Y%m%d')
    csv_path = os.path.join(RESULTS_PATH, f'metrics_comparison_{start_str}_{end_str}.csv')
    metrics_df.to_csv(csv_path, index=False, encoding='utf-8-sig')
    print(f"\n[Output] Metrics: {csv_path}")
    
    # --- Plot Equity Curve ---
    plt.figure(figsize=(14, 8))
    plt.plot(m1['equity_df'].index, m1['equity_df']['value'], label='Strat 1 (Split Hybrid + 2x)', color='blue', linewidth=2)
    plt.plot(m2['equity_df'].index, m2['equity_df']['value'], label='Strat 2 (Shared Pool)', color='purple', linewidth=1.5, alpha=0.8)
    plt.plot(m3['equity_df'].index, m3['equity_df']['value'], label='Strat 3 (Lump Hybrid)', color='red', linewidth=2.5)
    plt.plot(dca['equity_df'].index, dca['equity_df']['value'], label='Pure DCA', color='orange', linestyle='--', alpha=0.7)
    plt.plot(lump['equity_df'].index, lump['equity_df']['value'], label='Yearly Lump', color='gray', linestyle=':', alpha=0.7)
    
    plt.title(f'Strategy Comparison (Equity Curve) {start_str}~{end_str}')
    plt.ylabel('Value ($)')
    plt.legend()
    plt.grid(True, alpha=0.3)
    
    plot_path = os.path.join(RESULTS_PATH, f'comparison_equity_{start_str}_{end_str}.png')
    plt.savefig(plot_path)
    print(f"[Output] Chart: {plot_path}")
    
    # Save specific logs for Strat 3 analysis if needed
    if bt3.daily_action_summary:
        pd.DataFrame(bt3.daily_action_summary).to_csv(os.path.join(RESULTS_PATH, f'strat3_actions_{start_str}_{end_str}.csv'), index=False)
        pd.DataFrame(bt3.trades).to_csv(os.path.join(RESULTS_PATH, f'strat3_trades_{start_str}_{end_str}.csv'), index=False)

if __name__ == "__main__":
    main()
