# -*- coding: utf-8 -*-
"""
================================================================================
Daily Operations - V5 Intraday Dynamic Filter + Fixed LSTM
================================================================================
盤中執行腳本 - 使用 V5 模型 (對稱獎勵訓練) + 固定 LSTM 模型 + 動態體制濾網

**動態濾網特點**:
- 使用 MA120 判定市場體制 (Bull/Bear Mode)
- 熊市模式: 價格 < MA120 連續 3 天
- 熊市時啟用 Donchian 濾網 (Close > 10日 High)
- 牛市時無濾網限制

**Fixed LSTM 特點**:
- 不進行每日重訓，結果完全可重現
- 讀取 backtest_v5_dca_hybrid_dynamic_filter_fixed_lstm.py 產生的 lstm_info.json
- 使用與回測相同的 LSTM 模型 (T+20, T+5, T+1)

流程:
1. 從證交所 API 下載當日 OHLC 資料 (盤中即時)
2. 讀取回測產生的 lstm_info.json 取得 Fixed LSTM 路徑
3. 使用 Fixed LSTM 進行特徵工程與預測
4. 顯示目前市場體制 (牛市/熊市) 和濾網狀態
5. 輸出結果到 intraday_runs_v5_dynamic_filter_fixed/{date}_{time}/
6. 不寫入 twii_data_from_2000_01_01.csv

作者：Phil Liang (Generated by Gemini)
日期：2025-12-28
================================================================================
"""

import os
import sys
import shutil
import pickle
import subprocess
import json
import glob
from datetime import datetime, timedelta

# 設定 UTF-8 輸出
sys.stdout.reconfigure(encoding='utf-8')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
import yfinance as yf
# [v6.0] LSTM 已移除 - TensorFlow 不再需要

# =============================================================================
# 引用主系統
# =============================================================================
import ptrl_hybrid_system as core_system

# =============================================================================
# 設定路徑
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
INTRADAY_RUNS_PATH = os.path.join(PROJECT_PATH, 'intraday_runs_v5_dynamic_filter_fixed')  # V5 Dynamic Filter 專屬資料夾
CSV_FILE = os.path.join(PROJECT_PATH, 'twii_data_from_2000_01_01.csv')

# RL 模型路徑 (V5)
STRATEGY_V5_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v5')

# 回測結果路徑 (用於讀取持倉狀態和 LSTM 資訊)
BACKTEST_RESULTS_PATH = os.path.join(PROJECT_PATH, 'results_backtest_v5_dca_hybrid_dynamic_filter_fixed_lstm')


# =============================================================================
# 輔助函式: 互動式 CSV 選單
# =============================================================================
def interactive_select_csv(csv_files: list, default_index: int = -1) -> str:
    """
    使用方向鍵選擇 CSV 檔案
    
    Args:
        csv_files: CSV 檔案路徑列表
        default_index: 預設選擇的索引 (-1 表示最後一個)
    
    Returns:
        選擇的檔案路徑
    """
    import msvcrt
    
    sorted_files = sorted(csv_files)
    current_index = default_index if default_index >= 0 else len(sorted_files) - 1
    
    def render_menu():
        print("\n📂 請選擇回測 CSV (↑↓ 選擇, Enter 確認):")
        print("-" * 50)
        for i, f in enumerate(sorted_files):
            basename = os.path.basename(f)
            if i == current_index:
                print(f"  ▶ {basename} ◀")
            else:
                print(f"    {basename}")
        print("-" * 50)
    
    # 清除並顯示選單
    render_menu()
    
    while True:
        if msvcrt.kbhit():
            key = msvcrt.getch()
            
            # 方向鍵在 Windows 會先返回 0xe0 或 0x00
            if key in (b'\xe0', b'\x00'):
                arrow = msvcrt.getch()
                if arrow == b'H':  # 上
                    current_index = max(0, current_index - 1)
                elif arrow == b'P':  # 下
                    current_index = min(len(sorted_files) - 1, current_index + 1)
                
                # 清除螢幕並重繪
                print("\033[F" * (len(sorted_files) + 4), end='')  # 移動游標上移
                render_menu()
            
            elif key == b'\r':  # Enter
                print(f"\n✅ 已選擇: {os.path.basename(sorted_files[current_index])}")
                return sorted_files[current_index]
            
            elif key == b'\x1b':  # ESC
                print("\n⏹️ 取消選擇，使用預設 (最新)")
                return sorted_files[-1]


# =============================================================================
# 輔助函式: 讀取回測結果
# =============================================================================
def load_latest_backtest_status(backtest_start: str = None, interactive: bool = False) -> dict:
    """
    讀取回測 daily_action_strat1 CSV (Strategy 1: Leverage Mode)，取得持倉狀態與槓桿資訊
    
    Args:
        backtest_start: 可選，指定回測起始日期 (格式: YYYYMMDD 或 YYYY-MM-DD)
        interactive: 若為 True，則顯示互動式選單讓用戶選擇
    """
    import glob
    
    result = {
        'found': False,
        'csv_file': None,
        'last_date': None,
        'ai_position_count': 0,
        'dca_position_count': 0,
        'total_position_count': 0,
        'leveraged_mode': False,
        'current_leverage': 1.0,
        'positions_2x': 0,
        'peak_price': 0.0,
        'last_action': 'N/A',
        'last_note': 'N/A'
    }
    
    # 尋找 daily_action CSV (Strat 1)
    pattern = os.path.join(BACKTEST_RESULTS_PATH, 'daily_action_strat1_*.csv')
    csv_files = glob.glob(pattern)
    
    if not csv_files:
        print(f"[Backtest] 找不到回測結果: {pattern}")
        return result
    
    sorted_files = sorted(csv_files)
    
    # 選擇檔案
    if interactive and len(sorted_files) > 1:
        # 互動式選擇
        target_csv = interactive_select_csv(csv_files)
    elif backtest_start:
        # 命令列指定
        start_normalized = backtest_start.replace('-', '')
        matched = [f for f in csv_files if f'_{start_normalized}_' in f]
        if matched:
            target_csv = matched[0]
            print(f"[Backtest] 使用指定起始日: {backtest_start}")
        else:
            print(f"[Backtest] ⚠️ 找不到起始日 {backtest_start}，使用最新檔案")
            target_csv = sorted_files[-1]
    else:
        # 預設使用最新
        target_csv = sorted_files[-1]
        if len(sorted_files) > 1:
            print(f"[Backtest] 找到 {len(sorted_files)} 個回測結果，使用最新:")
        
    print(f"[Backtest] 讀取: {os.path.basename(target_csv)}")
    
    try:
        df = pd.read_csv(target_csv)
        if len(df) == 0:
            return result
        
        last_row = df.iloc[-1]
        
        # 計算目前的 Peak Price (依照 Strategy 1 邏輯)
        # 邏輯: 非槓桿模式時，更新最高價；槓桿模式時，最高價鎖定 (作為出場基準)
        current_peak_price = 0
        for _, row in df.iterrows():
            if 'leveraged_mode' in row:
                is_leveraged = bool(row['leveraged_mode'])
                price = float(row['price'])
                if not is_leveraged:
                    if price > current_peak_price:
                        current_peak_price = price
            else:
                current_peak_price = max(current_peak_price, float(row['price']))

        # Update Result
        result.update({
            'found': True,
            'csv_file': os.path.basename(target_csv),
            'last_date': last_row.get('date', 'N/A'),
            'ai_position_count': int(last_row.get('ai_position_count', 0)),
            'dca_position_count': int(last_row.get('dca_position_count', 0)),
            'total_position_count': int(last_row.get('total_position_count', 0)),
            'leveraged_mode': bool(last_row.get('leveraged_mode', False)),
            'current_leverage': float(last_row.get('current_leverage', 1.0)),
            'positions_2x': int(last_row.get('positions_2x', 0)),
            'peak_price': current_peak_price,
            'last_action': last_row.get('ai_action', 'N/A'),
            'last_note': last_row.get('note', 'N/A'),
            'open_positions': []
        })
        
        # 嘗試讀取 open_positions CSV (Strat 1)
        pos_csv = target_csv.replace('daily_action_strat1_', 'open_positions_strat1_')
        if os.path.exists(pos_csv):
            pos_df = pd.read_csv(pos_csv)
            result['open_positions'] = pos_df.to_dict('records')
            print(f"  未平倉持倉: {len(result['open_positions'])} 筆")
        else:
            print(f"  ⚠️ 找不到未平倉持倉檔案: {os.path.basename(pos_csv)}")
        
        leverage_status = "🔥 ON (2x)" if result['leveraged_mode'] else "OFF (1x)"
        print(f"  最後日期: {result['last_date']}")
        print(f"  持倉狀態: 總{result['total_position_count']}倉 (DCA{result['dca_position_count']} + AI{result['ai_position_count']})")
        print(f"  槓桿狀態: {leverage_status} | Peak: {current_peak_price:,.2f}")
        
    except Exception as e:
        print(f"[Error] 讀取回測 CSV 失敗: {e}")
    
    return result


# =============================================================================
# Step 0: 建立盤中專屬工作區
# =============================================================================
def create_intraday_workspace(date_str: str, time_str: str) -> dict:
    folder_name = f"{date_str}_{time_str}"
    intraday_path = os.path.join(INTRADAY_RUNS_PATH, folder_name)
    paths = {
        'root': intraday_path,
        # [v6.0] LSTM 已移除 - 不再需要 lstm_models 資料夾
        'cache': os.path.join(intraday_path, 'cache'),
        'reports': os.path.join(intraday_path, 'reports'),
    }
    for key, path in paths.items():
        os.makedirs(path, exist_ok=True)
    print(f"[Workspace] 建立盤中工作區: {intraday_path}")
    return paths


# =============================================================================
# 輔助函式: 取得盤中 OHLC
# =============================================================================
def fetch_intraday_ohlc(ticker: str = "^TWII") -> tuple:
    """
    從證交所盤中即時 API 下載當日 OHLC 資料
    """
    import requests
    
    print(f"\n[Download] 正在從證交所盤中 API 下載即時資料...")
    url = "https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=tse_t00.tw"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        'Accept': 'application/json',
        'Referer': 'https://mis.twse.com.tw/stock/index.jsp'
    }
    
    try:
        r = requests.get(url, headers=headers, timeout=10)
        r.raise_for_status()
        data = r.json()
        msg_array = data.get('msgArray', [])
        
        if not msg_array:
            print("[Error] 證交所 API 無資料 (可能非交易時段)")
            return None
        
        item = msg_array[0]
        raw_date = item.get('d', '')
        if len(raw_date) == 8:
            date_str = f"{raw_date[:4]}-{raw_date[4:6]}-{raw_date[6:8]}"
        else:
            date_str = datetime.now().strftime('%Y-%m-%d')
        
        o = float(item.get('o', 0))
        h = float(item.get('h', 0))
        l = float(item.get('l', 0))
        z = float(item.get('z', 0))
        time_str = item.get('t', 'N/A')
        
        print(f"  📅 日期: {date_str}")
        print(f"  ⏰ 時間: {time_str}")
        print(f"  📈 Open: {o:.2f}")
        print(f"  📊 High: {h:.2f}")
        print(f"  📉 Low: {l:.2f}")
        print(f"  💰 即時價: {z:.2f}")
        
        return (date_str, o, h, l, z)
        
    except Exception as e:
        print(f"[Error] 取得盤中資料失敗: {e}")
        return None


# =============================================================================
# 輔助函式: 取得前 5 日成交量平均
# =============================================================================
def get_avg_volume_from_csv(n_days: int = 5) -> float:
    print(f"\n[Volume] 從 CSV 計算前 {n_days} 日成交量平均...")
    try:
        df = pd.read_csv(CSV_FILE)
        volumes = df['volume'].tail(n_days)
        avg_vol = volumes.mean()
        print(f"  📈 平均成交量: {avg_vol:.2f} 億元")
        return avg_vol
    except Exception as e:
        print(f"[Error] 讀取 CSV 失敗: {e}")
        return 3000.0


# =============================================================================
# 輔助函式: 建立暫存 CSV
# =============================================================================
def create_temp_csv_with_intraday(intraday_data: tuple, avg_volume: float, workspace: dict) -> str:
    print("\n[TempCSV] 建立暫存訓練資料...")
    df = pd.read_csv(CSV_FILE)
    date_str, o, h, l, c = intraday_data
    dt = datetime.strptime(date_str, '%Y-%m-%d')
    csv_date = f"{dt.year}/{dt.month}/{dt.day}"
    
    last_date = df['date'].iloc[-1]
    last_dt = datetime.strptime(last_date, '%Y/%m/%d')
    
    if last_dt.date() == dt.date():
        print(f"  [Info] 更新 {csv_date} 的資料為盤中數據")
        df.iloc[-1] = [csv_date, o, h, l, c, avg_volume]
    else:
        print(f"  [Info] 加入盤中資料: {csv_date}")
        new_row = pd.DataFrame({
            'date': [csv_date], 'open': [o], 'high': [h], 'low': [l], 'close': [c], 'volume': [avg_volume]
        })
        df = pd.concat([df, new_row], ignore_index=True)
    
    temp_csv_path = os.path.join(workspace['cache'], 'temp_twii_data.csv')
    df.to_csv(temp_csv_path, index=False)
    print(f"  ✅ 暫存 CSV 已建立: {temp_csv_path}")
    return temp_csv_path


# =============================================================================
# [v6.0] LSTM 已移除 - 以下函式已刪除:
# - load_lstm_info_from_backtest()
# - load_fixed_lstm_for_intraday()
# =============================================================================
# =============================================================================
# Step 2: 隔離式特徵工程
# =============================================================================
def feature_engineering(intraday_data: tuple, avg_volume: float) -> pd.DataFrame:
    """
    特徵工程 (使用盤中資料)
    
    [v6.0] LSTM 已移除
    """
    print("\n" + "=" * 60)
    print("🔧 Step 2: 特徵工程")
    print("=" * 60)
    
    # 合併資料
    print("[Merge] 合併歷史資料與盤中資料...")
    df = pd.read_csv(CSV_FILE)
    df['date'] = pd.to_datetime(df['date'], format='%Y/%m/%d')
    df = df.set_index('date')
    df = df.rename(columns={'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Close', 'volume': 'Volume'})
    
    date_str, o, h, l, c = intraday_data
    intraday_dt = pd.Timestamp(date_str)
    
    if intraday_dt in df.index:
        print(f"  [Info] 更新 {date_str} 的資料為盤中數據")
        df.loc[intraday_dt] = [o, h, l, c, avg_volume]
    else:
        print(f"  [Info] 加入盤中資料: {date_str}")
        new_row = pd.DataFrame({'Open': [o], 'High': [h], 'Low': [l], 'Close': [c], 'Volume': [avg_volume]}, index=[intraday_dt])
        df = pd.concat([df, new_row])
    
    df = df.sort_index()
    print(f"[Compute] Generating features for ^TWII...")
    return core_system.calculate_features(df, df, ticker="^TWII", use_cache=False)


# =============================================================================
# Step 3: V5 策略推論 (動態濾網)
# =============================================================================
def calculate_regime_status(df: pd.DataFrame, lookback: int = 3) -> dict:
    """
    計算目前市場體制 (Bull/Bear Mode) 和濾網狀態
    
    邏輯:
    - 熊市模式: 價格 < MA120 連續 `lookback` 天
    - 熊市時啟用 Donchian 濾網 (Close > 10日 High)
    - 牛市時無濾網限制
    """
    last_rows = df.tail(lookback + 1)
    
    # 檢查 MA120 是否存在
    if 'MA120' not in df.columns:
        return {
            'regime': 'BULL',
            'bear_days': 0,
            'ma120': 0,
            'donchian_pass': True,
            'filter_active': False,
            'reason': 'MA120 不存在，預設牛市'
        }
    
    last_row = df.iloc[-1]
    close_price = float(last_row['Close'])
    ma120 = float(last_row.get('MA120', 0))
    donchian_pass = bool(last_row.get('Signal_Buy_Filter', False))
    
    # 計算連續低於 MA120 的天數
    bear_days = 0
    for i in range(len(last_rows) - 1, -1, -1):
        row = last_rows.iloc[i]
        if float(row['Close']) < float(row.get('MA120', 0)):
            bear_days += 1
        else:
            break
    
    # 判定體制
    if bear_days >= lookback:
        regime = 'BEAR'
        filter_active = True
        reason = f'價格 < MA120 連續 {bear_days} 天，啟用 Donchian 濾網'
    else:
        regime = 'BULL'
        filter_active = False
        reason = f'牛市模式，無濾網限制'
    
    return {
        'regime': regime,
        'bear_days': bear_days,
        'ma120': ma120,
        'close': close_price,
        'donchian_pass': donchian_pass,
        'filter_active': filter_active,
        'reason': reason
    }


def v5_inference(workspace: dict, df: pd.DataFrame, open_positions: list = None, current_price: float = None,
                 sell_threshold: float = 0.6, buy_consensus_threshold: float = 0.5) -> dict:
    """
    V5 策略推論 (動態濾網)
    
    Args:
        workspace: 工作區資訊
        df: 特徵 DataFrame
        open_positions: 從回測讀取的 AI 持倉清單 (含 buy_price, buy_date)
        current_price: 盤中即時價 (用於計算各持倉報酬率)
        sell_threshold: 賣出信心門檻 (預設 0.5)
        buy_consensus_threshold: 買入共識門檻 (預設 0.8)
    """
    print("\n" + "=" * 60)
    print("🎯 Step 3: V5 策略推論 (動態濾網)")
    print(f"   ⚙️ Consensus: Sell Threshold > {sell_threshold} | Buy Veto > {buy_consensus_threshold}")
    print("=" * 60)
    
    from stable_baselines3 import PPO
    latest = df.iloc[-1]
    
    # 如果沒傳入 current_price，從 df 取得
    if current_price is None:
        current_price = float(latest['Close'])
    
    # 計算體制狀態
    regime_status = calculate_regime_status(df)
    regime = regime_status['regime']
    filter_active = regime_status['filter_active']
    donchian_pass = regime_status['donchian_pass']
    
    # 顯示體制狀態
    regime_icon = "🐂" if regime == 'BULL' else "🐻"
    print(f"  [體制] {regime_icon} {regime} Mode (熊市天數: {regime_status['bear_days']})")
    print(f"  [MA120] {regime_status.get('ma120', 0):,.2f} | Close: {current_price:,.2f}")
    filter_state = "ON (啟用中)" if filter_active else "OFF (未啟用)"
    donchian_state = "✅通過" if donchian_pass else "❌未通過"
    print(f"  [濾網] 動態濾網: {filter_state} | Donchian: {donchian_state}")
    
    # 保留 filter 資訊
    signal_buy_filter = donchian_pass
    
    features = np.array([latest.get(col, 0.0) for col in core_system.FEATURE_COLS], dtype=np.float32).reshape(1, -1)
    features = np.nan_to_num(features, nan=0.0, posinf=1.0, neginf=-1.0)
    
    # 載入 V5 模型
    buy_path = os.path.join(STRATEGY_V5_PATH, 'ppo_buy_twii_final.zip')
    sell_path = os.path.join(STRATEGY_V5_PATH, 'ppo_sell_twii_final.zip')
    
    if not os.path.exists(buy_path):
        return {'error': 'V5 Model not found', 'filter_status': signal_buy_filter, 'regime_status': regime_status}

    try:
        buy_agent = PPO.load(buy_path)
        sell_agent = PPO.load(sell_path)
        
        # ===== Buy Agent =====
        b_act, _ = buy_agent.predict(features, deterministic=True)
        b_obs = buy_agent.policy.obs_to_tensor(features)[0]
        b_prob = buy_agent.policy.get_distribution(b_obs).distribution.probs.detach().cpu().numpy()[0]
        
        ai_action = 'BUY' if b_act[0] == 1 else 'WAIT'
        buy_prob = float(b_prob[1]) if b_act[0] == 1 else float(b_prob[0])
        
        # 動態濾網邏輯: 熊市時啟用濾網
        if filter_active:
            # 熊市模式: 必須通過 Donchian 才能買
            if ai_action == 'BUY' and not donchian_pass:
                buy_signal = 'FILTERED'
                filter_note = "🚫被濾網擋下 (熊市 + Donchian未通過)"
            else:
                buy_signal = ai_action
                filter_note = "✅通過" if donchian_pass else "❌未通過"
        else:
            # 牛市模式: 無濾網限制
            buy_signal = ai_action
            filter_note = "🐂牛市-無濾網"
        
        print(f"  [V5] AI 判斷: {ai_action} ({buy_prob:.1%})")
        print(f"  [V5] 最終決策: {buy_signal} | {filter_note}")
        
        # ===== Sell Agent (真實持倉分析) =====
        position_decisions = []
        
        if open_positions and len(open_positions) > 0:
            print(f"  [V5] 分析 {len(open_positions)} 筆 AI 持倉...")
            
            for pos in open_positions:
                buy_price = float(pos.get('buy_price', 0))
                buy_date = pos.get('buy_date', 'N/A')
                
                if buy_price > 0:
                    # 計算真實報酬率
                    current_return = current_price / buy_price
                    return_pct = (current_return - 1) * 100
                    
                    # 構建 Sell Agent 的觀察值 (特徵 + 報酬率)
                    s_feat = np.concatenate([features[0], [current_return]]).reshape(1, -1).astype(np.float32)
                    s_act, _ = sell_agent.predict(s_feat, deterministic=True)
                    
                    # 取得機率分布以計算信心
                    s_obs = sell_agent.policy.obs_to_tensor(s_feat)[0]
                    s_prob = sell_agent.policy.get_distribution(s_obs).distribution.probs.detach().cpu().numpy()[0]
                    
                    sell_action = 'SELL' if s_act[0] == 1 else 'HOLD'
                    sell_conf = float(s_prob[1]) if s_act[0] == 1 else float(s_prob[0])
                    
                    # 判斷是否觸發停損 (硬性規則: -8%)
                    sell_action = 'SELL' if s_act[0] == 1 else 'HOLD'
                    sell_conf = float(s_prob[1]) if s_act[0] == 1 else float(s_prob[0])
                    
                    # 判斷是否觸發停損 (硬性規則: -8%)
                    triggered_stop_loss = current_return < 0.92

                    # 🔥 Agent Consensus Logic
                    is_sell_signal = (s_act[0] == 1 and sell_conf > sell_threshold)
                    is_consensus_hold = False
                    veto_reason = ""
                    
                    if is_sell_signal and not triggered_stop_loss:
                        # 🔥 只有當 Buy Agent 真心想買 (Action=1) 且信心夠高時，才否決賣出
                        if ai_action == 'BUY' and buy_prob > buy_consensus_threshold:
                            is_consensus_hold = True
                            veto_reason = f"🚫 Consensus Veto (Buy Conf {buy_prob:.1%} > {buy_consensus_threshold})"
                            print(f"    -> Sell Signal Vetoed! {veto_reason}")

                    final_action = 'HOLD'
                    if triggered_stop_loss:
                        final_action = 'SELL'
                    elif is_sell_signal and not is_consensus_hold:
                        final_action = 'SELL'
                    
                    position_decisions.append({
                        'buy_date': buy_date,
                        'buy_price': buy_price,
                        'current_return': current_return,
                        'return_pct': return_pct,
                        'action': sell_action,
                        'confidence': sell_conf,
                        'triggered_stop_loss': triggered_stop_loss,
                        'is_consensus_hold': is_consensus_hold,
                        'veto_reason': veto_reason,
                        'final_action': final_action
                    })
        else:
            print(f"  [V5] 無 AI 持倉，跳過 Sell Agent 分析")
        
        return {
            'filter_status': signal_buy_filter,
            'buy_signal': buy_signal,
            'buy_prob': buy_prob,
            'ai_action': ai_action,
            'position_decisions': position_decisions,
            'regime_status': regime_status  # 體制狀態
        }
    except Exception as e:
        print(f"  [Error] V5 Inference: {e}")
        return {'error': str(e), 'filter_status': signal_buy_filter, 'regime_status': regime_status}


# =============================================================================
# Step 4: 輸出盤中報告
# =============================================================================
def generate_intraday_report(workspace: dict, df: pd.DataFrame, res: dict, date_str: str, intraday_data: tuple, avg_volume: float, backtest_status: dict = None):
    print("\n" + "=" * 60)
    print("📊 Step 4: 盤中戰情儀表板 (V5 Dynamic Filter)")
    print("=" * 60)
    
    last = df.iloc[-1]
    filter_status = res.get('filter_status', False)
    _, o, h, l, c = intraday_data
    
    lines = []
    lines.append("=" * 50)
    lines.append(f"📅 V5 盤中即時分析 (動態濾網) - {date_str}")
    lines.append(f"⏰ 更新時間: {datetime.now().strftime('%H:%M:%S')}")
    lines.append("=" * 50)
    lines.append(f"📊 Open:  {o:,.2f}")
    lines.append(f"📈 High:  {h:,.2f}")
    lines.append(f"📉 Low:   {l:,.2f}")
    lines.append(f"💰 Close: {c:,.2f} (即時)")
    lines.append(f"📦 Volume: {avg_volume:.2f} 億元 (前5日平均估計)")
    lines.append("-" * 50)
    
    # 動態體制狀態 (核心資訊)
    regime_status = res.get('regime_status', {})
    regime = regime_status.get('regime', 'BULL')
    bear_days = regime_status.get('bear_days', 0)
    ma120 = regime_status.get('ma120', 0)
    filter_active = regime_status.get('filter_active', False)
    donchian_pass = regime_status.get('donchian_pass', False)
    
    regime_icon = "🐂" if regime == 'BULL' else "🐻"
    lines.append(f"📊 [市場體制監控] (MA120 動態濾網)")
    lines.append(f"   體制: {regime_icon} {regime} Mode")
    lines.append(f"   MA120: {ma120:,.2f} | 即時價: {c:,.2f}")
    
    if regime == 'BEAR':
        lines.append(f"   熊市天數: {bear_days} 天 (連續低於 MA120)")
        donchian_icon = "✅" if donchian_pass else "🚫"
        lines.append(f"   濾網狀態: 🔴 啟用中 | Donchian: {donchian_icon} {'通過' if donchian_pass else '未通過'}")
        if not donchian_pass:
            lines.append(f"   ⚠️ AI 買入訊號將被擋下 (需突破 10日 High)")
    else:
        lines.append(f"   濾網狀態: 🟢 未啟用 (牛市自由模式)")
        lines.append(f"   ℹ️ AI 可自由判斷買賣，無濾網限制")
    lines.append("-" * 50)
    
    # 槓桿狀態 (Strategy 1 Only)
    if backtest_status and 'leveraged_mode' in backtest_status:
        lev_mode = backtest_status['leveraged_mode']
        peak_price = backtest_status.get('peak_price', 0)
        
        lev_icon = "🔥" if lev_mode else "❄️"
        lev_str = "ON (2倍槓桿)" if lev_mode else "OFF (1倍槓桿)"
        
        lines.append(f"⚡ [2x 槓桿監控] (Strategy 1)")
        lines.append(f"   狀態: {lev_icon} {lev_str}")
        
        if peak_price > 0:
            current_close = float(c)
            dd_pct = (current_close - peak_price) / peak_price
            lines.append(f"   高點: {peak_price:,.2f} | 目前跌幅: {dd_pct*100:.2f}%")
            if not lev_mode:
                trigger_price = peak_price * 0.92  # 8% threshold
                dist_to_trigger = (current_close - trigger_price) / current_close
                lines.append(f"   觸發: {trigger_price:,.2f} (距離: {dist_to_trigger*100:.2f}%)")
            else:
                lines.append(f"   退出: {peak_price:,.2f} (回到高點即退出)")
        lines.append("-" * 50)

    # [v6.0] LSTM 已移除 - 不再輸出 LSTM 預測

    # V5 顯性特徵列表
    lines.append("📐 [關鍵特徵]")
    lines.append(f"   MA20 動能: {last.get('Feat_MA20_Slope', 0)*100:+.2f}%  (>0 轉強)")
    lines.append(f"   市場體制: {last.get('Feat_Trend_Gap', 0)*100:+.2f}%  (>0 多頭結構)")
    lines.append(f"   短線乖離: {last.get('Feat_Bias_MA20', 0)*100:+.2f}%")
    lines.append(f"   季線距離: {last.get('Feat_Dist_MA60', 0)*100:+.2f}%")
    lines.append(f"   年線位置: {last.get('Feat_Dist_MA240', 0)*100:+.2f}%  (>0 長多)")
    lines.append(f"   相對量能: {last.get('Feat_Vol_Ratio', 0):.2f}x   (>1.0 放量)")
    lines.append("-" * 50)
    
    # V5 RL
    lines.append("🤖 [操盤手 V5] (對稱獎勵 + 動態濾網)")
    if 'error' in res:
        lines.append(f"   ❌ 錯誤: {res['error']}")
    else:
        buy_signal = res['buy_signal']
        buy_prob = res['buy_prob']
        buy_icon = "🚀" if buy_signal == 'BUY' else "💤" if buy_signal == 'WAIT' else "🚫"
        
        lines.append(f"   🛒 買入訊號: {buy_icon} {buy_signal} ({buy_prob:.1%})")

    lines.append("-" * 50)
    
    # Advice (動態濾網版)
    buy_signal = res.get('buy_signal', 'N/A')
    ai_action = res.get('ai_action', 'N/A')
    
    if buy_signal == 'BUY':
        advice = "⭐⭐ V5 強力買進 (Strong Buy) ⭐⭐"
    elif buy_signal == 'FILTERED':
        advice = "🚫 AI 想買但被濾網擋下 (熊市防線)"
    elif buy_signal == 'WAIT' or ai_action == 'WAIT':
        advice = "💤 空手觀望 (Wait)"
    else:
        advice = "❓ 訊號不明"
    
    # 標注體制狀態
    regime_note = f"{regime_icon}{regime}" if regime else "BULL"
    advice += f" [{regime_note}]"
        
    lines.append(f"💡 盤中建議: {advice}")
    lines.append("-" * 50)
    
    # 回測持倉狀態
    if backtest_status and backtest_status.get('found'):
        # 解析 CSV 檔名中的日期
        csv_file = backtest_status.get('csv_file', 'N/A')
        # 檔名格式: daily_action_strat2_YYYYMMDD_YYYYMMDD.csv
        import re
        date_match = re.search(r'(\d{8})_(\d{8})\.csv$', csv_file)
        if date_match:
            start_date = f"{date_match.group(1)[:4]}-{date_match.group(1)[4:6]}-{date_match.group(1)[6:8]}"
            end_date = f"{date_match.group(2)[:4]}-{date_match.group(2)[4:6]}-{date_match.group(2)[6:8]}"
            date_range_str = f"{start_date} ~ {end_date}"
        else:
            date_range_str = csv_file
        
        lines.append(f"💼 [回測持倉狀態] 檔案: {csv_file}")
        lines.append(f"   📅 回測期間: {date_range_str}")
        lines.append(f"   🏛️  DCA 倉位: {backtest_status['dca_position_count']} 倉")
        lines.append(f"   🤖 AI 倉位: {backtest_status['ai_position_count']} 倉")
        lines.append(f"   📊 總倉數: {backtest_status['total_position_count']} 倉")
        lines.append(f"   📝 最後操作: {backtest_status['last_note']}")
        
        # 預測今日操作
        lines.append("-" * 50)
        lines.append("🔮 [今日預測] (基於盤中價格模擬)")
        
        ai_action = res.get('ai_action', 'WAIT')
        ai_positions = backtest_status['ai_position_count']
        dca_positions = backtest_status['dca_position_count']
        
        # 預測買入 (V5: 無濾網限制，純看 AI 決策)
        predicted_buy = 0
        if ai_action == 'BUY':
            lines.append(f"   🟢 買入預測: AI+1倉 (V5 無濾網限制, AI建議BUY)")
            predicted_buy = 1
        else:
            lines.append(f"   ⚪ 買入預測: 無 (AI:{ai_action})")
        
        # 預測賣出 (使用 position_decisions)
        position_decisions = res.get('position_decisions', [])
        predicted_sell = 0
        current_price = float(intraday_data[4])  # intraday_data = (date, o, h, l, c)
        
        if position_decisions:
            lines.append("-" * 50)
            lines.append("📦 [AI持倉明細 + Sell Agent 判斷]")
            
            for i, pd in enumerate(position_decisions, 1):
                buy_date = pd.get('buy_date', 'N/A')
                buy_price = pd.get('buy_price', 0)
                return_pct = pd.get('return_pct', 0)
                action = pd.get('action', 'HOLD')
                confidence = pd.get('confidence', 0)
                final_action = pd.get('final_action', 'HOLD')
                triggered_stop_loss = pd.get('triggered_stop_loss', False)
                
                # 決定顯示格式
                # 決定顯示格式
                if triggered_stop_loss:
                    status_icon = "🔴 SELL"
                    reason = f"停損觸發 (AI: {action} {confidence:.1%})"
                elif final_action == 'SELL':
                    status_icon = "🔴 SELL"
                    reason = f"AI決定 ({confidence:.1%})"
                elif pd.get('is_consensus_hold', False):
                    status_icon = "🟢 HOLD"
                    reason = f"AI賣訊被否決 ({pd.get('veto_reason')})"
                else:
                    status_icon = "🟢 HOLD"
                    reason = f"AI決定 ({confidence:.1%})"
                
                lines.append(f"   #{i} 買入: {buy_date} @ {buy_price:,.2f}")
                lines.append(f"       報酬: {return_pct:+.2f}% | {status_icon} {reason}")
                
                if final_action == 'SELL':
                    predicted_sell += 1
        elif ai_positions > 0:
            lines.append(f"   ⚠️ 無持倉明細資料")
        else:
            lines.append(f"   ⚪ 賣出預測: 無 (AI 無持倉)")
        
        # 計算預估總倉
        predicted_ai = ai_positions + predicted_buy - predicted_sell
        predicted_total = dca_positions + predicted_ai
        
        lines.append("-" * 50)
        lines.append("📊 [預估收盤後倉位]")
        lines.append(f"   DCA: {dca_positions} 倉 (不變)")
        change = predicted_buy - predicted_sell
        change_str = f"+{change}" if change > 0 else str(change) if change < 0 else "±0"
        lines.append(f"   AI:  {ai_positions} → {predicted_ai} 倉 ({change_str})")
        lines.append(f"   總計: {backtest_status['total_position_count']} → {predicted_total} 倉")
        
    else:
        lines.append("💼 [回測持倉狀態] 未找到回測結果")
        lines.append("   請先執行: python backtest_v5_dca_hybrid_no_filter_fixed_lstm.py --start 2025-01-02")
    
    lines.append("=" * 50)
    
    report = "\n".join(lines)
    print(report)
    
    # Save
    with open(os.path.join(workspace['reports'], 'intraday_summary.txt'), 'w', encoding='utf-8') as f:
        f.write(report)
    
    json_data = {
        'date': date_str,
        'filter_status': filter_status,
        'market': {'close': c, 'volume_est': avg_volume},
        # [v6.0] LSTM 已移除 - 不再輸出 LSTM 預測
        'v5': res,
        'advice': advice
    }
    with open(os.path.join(workspace['reports'], 'intraday_summary.json'), 'w', encoding='utf-8') as f:
        json.dump(json_data, f, indent=2, ensure_ascii=False)
    
    print(f"\n[Report] 已儲存至: {workspace['reports']}")


# =============================================================================
# Main
# =============================================================================
def main():
    import argparse
    
    parser = argparse.ArgumentParser(
        description='V5 盤中分析系統 (Dynamic Filter + Fixed LSTM)',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
使用範例:
  python daily_ops_v5_intraday_dynamic_filter_fixed_lstm.py                    # 使用最新回測結果
  python daily_ops_v5_intraday_dynamic_filter_fixed_lstm.py -i                 # 互動式選擇回測 CSV
  python daily_ops_v5_intraday_dynamic_filter_fixed_lstm.py --backtest-start 2025-01-02  # 指定回測起始日
        '''
    )
    parser.add_argument(
        '-i', '--interactive',
        action='store_true',
        help='互動式選擇回測 CSV 檔案 (使用方向鍵)'
    )
    parser.add_argument(
        '--backtest-start', 
        type=str, 
        default=None,
        help='回測起始日期 (YYYY-MM-DD 或 YYYYMMDD 格式)'
    )
    parser.add_argument('--sell-threshold', type=float, default=0.6, help='Confidence threshold for sell signals')
    parser.add_argument('--buy-consensus-threshold', type=float, default=0.5, help='Buy confidence threshold to veto sell signals')
    args = parser.parse_args()
    
    now = datetime.now()
    date_str = now.strftime('%Y-%m-%d')
    time_str = now.strftime('%H%M%S')
    
    print(f"🚀 V5 盤中分析系統 (Dynamic Filter) - {date_str} {time_str}")
    
    # Step 0
    ws = create_intraday_workspace(date_str, time_str)
    
    # Step 0.4: 讀取回測持倉狀態
    print("\n[Backtest] 讀取回測持倉狀態...")
    backtest_status = load_latest_backtest_status(args.backtest_start, interactive=args.interactive)
    
    # Step 0.5
    intraday_data = fetch_intraday_ohlc("^TWII")
    if not intraday_data: sys.exit(1)
    
    # Step 0.6
    avg_volume = get_avg_volume_from_csv(5)
    
    # [v6.0] LSTM 已移除 - 跳過 Step 1
    
    # Step 2: 特徵工程
    df = feature_engineering(intraday_data, avg_volume)
    
    # Step 3: V5 策略推論 (傳入真實持倉資訊)
    open_positions = backtest_status.get('open_positions', []) if backtest_status else []
    current_price = float(intraday_data[4])  # intraday_data = (date, o, h, l, c)
    res = v5_inference(
        ws, df, 
        open_positions=open_positions, 
        current_price=current_price,
        sell_threshold=args.sell_threshold,
        buy_consensus_threshold=args.buy_consensus_threshold
    )
    
    # Step 4
    generate_intraday_report(ws, df, res, intraday_data[0], intraday_data, avg_volume, backtest_status)
    print("Done.")

if __name__ == "__main__":
    main()
